(function(g){var window=this;'use strict';var zt=function(B){B.isActive()||B.start()},bL=function(B){var l={languageCode:B.languageCode,
languageName:B.languageName,displayName:g.KV(B),kind:B.kind,name:B.name,id:B.id,is_servable:B.W,is_default:B.isDefault,is_translateable:B.isTranslateable,vss_id:B.vssId};B.xtags&&(l.xtags=B.xtags);B.captionId&&(l.captionId=B.captionId);B.translationLanguage&&(l.translationLanguage=B.translationLanguage);return l},Sfp=function(B,l){var p=new g.JY;
p.languageCode=B.languageCode;p.languageName=B.languageName;p.name=B.name;p.displayName=B.displayName;p.kind=B.kind;p.isDefault=!1;p.W=B.W;p.isTranslateable=B.isTranslateable;p.vssId=B.vssId;p.url=B.url;p.translationLanguage=l;B.xtags&&(p.xtags=B.xtags);B.captionId&&(p.captionId=B.captionId);return p},os=function(B,l){return l?B.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},jbt=function(B){return g.Lk(B)||B.S("web_enable_caption_language_preference_stickiness")},ggi=async function(B,l){B=
B+"|"+l;
l=await g.Rc();if(!l)throw g.sn("gct");return(await g.c4(l)).get("captions",B)},Ikt=function(B,l,p){ggi(B,l).then(a=>{a&&p(a.trackData,new g.JY(a.metadata))})},FU=function(B){if(!Owl.test(B))throw Error("'"+B+"' is not a valid hex color");
B.length==4&&(B=B.replace(Tfk,"#$1$1$2$2$3$3"));B=B.toLowerCase();B=parseInt(B.slice(1),16);return[B>>16,B>>8&255,B&255]},wET=function(){var B={},l="suggest_correction"in g.s3?g.s3.suggest_correction:"Edit caption";
l=l||"";for(let p in B){let a=()=>String(B[p]);
l=l.replace(new RegExp("\\$\\{"+p+"\\}","gi"),a);l=l.replace(new RegExp("\\$"+p,"gi"),a)}return l},hp=function(){return g.IG("yt-player-caption-display-settings")},e9n=function(B,l){g.OQ(l,p=>B.equals(p))||l.push(B)},sR=function(B,l){switch(l.kind){case "asr":e9n(l,B.O);
break;default:e9n(l,B.A)}},A6p=async function(B,l,p){B.A=g.Hf(l,p)},$8x=function(B,l){var p=g.ro(B.segments,l);
p>=0||p<0&&(-p-1)%2===1||(p=-p-1,p>0&&l-B.segments[p-1]===1&&p<B.segments.length&&B.segments[p]-l===1?(g.AF(B.segments,p),g.AF(B.segments,p-1)):p>0&&l-B.segments[p-1]===1?B.segments[p-1]=l:p<B.segments.length&&B.segments[p]-l===1?B.segments[p]=l:(g.nx(B.segments,p,0,l),g.nx(B.segments,p+1,0,l)))},QbP=function(B){return B.W&&B.W.D?B.W.D+B.player.gd()<B.player.getCurrentTime():!1},fkP=function(B,l){if(B.policy.HA&&B.player.CE()){var p=g.xf(l,B.policy,{});
p.set("pot",B.player.CE());p=p.n2()}else p=g.xf(l,B.policy,{}).n2();var a={format:"RAW",withCredentials:!0};if(B.policy.kh){a.method="POST";let q=l.D;q&&Object.keys(q).length>0?a.postBody=g.$i(q,g.mA):a.postBody=(0,g.LR)([120,0])}B.G&&(a.responseType="arraybuffer");var x=++B.uH,C=(0,g.Q)();B.A=g.u3(p,a,3,100,-1,q=>{q.errorCode==="net.timeout"&&B.player.K("capnt",{rn:x++})}).then(q=>{if(B.policy.ib&&x%100===1){var R=(0,g.Q)();
B.player.K("caprsp",{rn:x,ms:R-C,kb:(q.xhr.responseText.length/1024).toFixed()})}a:{q=q.xhr;B.iH();if(B.O){var m=!(B.G?q.response:q.responseText)||q.status>=400;if(R=g.uC(q)){q=g.xf(B.O,B.policy,{});B.O.vA(q,R);fkP(B,B.O);break a}m?B.player.K("capfail",{status:q.status}):(g.hy("fcb_r",(0,g.Q)(),B.player.getVideoData()?.Z||""),R=B.O.w8[0],m=R.zo,B.L!=null&&B.V!==m&&(B.G?B.L(q.response,(R.startTime+B.player.gd())*1E3):B.L(q.responseText,(R.startTime+B.player.gd())*1E3),B.V=m))}B.O=null;B.A=null}}).nw(q=>
{B.O=null;
B.A=null;B.player.K("capfail",{rn:x,status:q.xhr?.status})});
B.O=l;$8x(B.D,B.O.w8[0].zo)},YfE=function(B,l){return l!=null&&l in B.A.W?B.A.W[l]:null},KPP=function(B,l,p){var a=[];
for(let x in B.A.W){if(!B.A.W.hasOwnProperty(x))continue;let C=B.A.W[x];if(g.re(C,p||null)){let q=C.info.captionTrack;q&&q.languageCode===l&&a.push(C)}}return a.length?a[0]:null},ng7=function(B,l){var p=[];
for(let x in B.A.W){if(!B.A.W.hasOwnProperty(x))continue;var a=B.A.W[x];if(g.re(a,l||null)){let C=a.info.id,q=C,R=`.${C}`,m="",t="";if(a=a.info.captionTrack)C=a.languageCode,q=a.displayName,R=a.vssId,m=a.kind,t=a.id;p.push(new g.JY({id:x,languageCode:C,languageName:q,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:R,kind:m,captionId:t}))}}return p},kx=function(B){if(typeof DOMParser!="undefined")return g.mf(new DOMParser,g.Vh(B),"application/xml");
throw Error("Your browser does not support loading xml documents");},y6W=function(B,l,p,a){var x=l/360*16;
l>=B&&(B=640,a>p*1.3&&(B=480),x=p/B*16);return x},U8W=function(B){var l=1+.25*(B.fontSizeIncrement||0);
if(B.offset===0||B.offset===2)l*=.8;return l},r6P=function(B,l){var p="vertical-rl";
B.W.f$===1&&(p="vertical-lr");g.sp&&(p=p==="vertical-lr"?"tb-lr":"tb-rl");g.s4(l,"-o-writing-mode",p);g.s4(l,"-webkit-writing-mode",p);g.s4(l,"writing-mode",p);g.s4(l,"text-orientation","upright");g.Kz(l,"ytp-vertical-caption");B.O.params.YM===3&&(g.s4(l,"text-orientation",""),g.s4(l,"transform","rotate(180deg)"))},BSi=function(B,l){var p={},a=l.background?l.background:B.W.ii.background;
if(l.backgroundOpacity!=null||l.background){var x=l.backgroundOpacity!=null?l.backgroundOpacity:B.W.ii.backgroundOpacity;a=FU(a);p.background="rgba("+a[0]+","+a[1]+","+a[2]+","+x+")";B.mf&&(p["box-decoration-break"]="clone",p["border-radius"]=`${B.bH*.375}px`)}if(l.fontSizeIncrement!=null||l.offset!=null)p["font-size"]=`${B.Hi*U8W(l)}px`;a=1;x=l.color||B.W.ii.color;if(l.color||l.textOpacity!=null)x=FU(x),a=l.textOpacity==null?B.W.ii.textOpacity:l.textOpacity,x="rgba("+x[0]+","+x[1]+","+x[2]+","+a+
")",p.color=x,p.fill=x;var C=l.charEdgeStyle;C===0&&(C=void 0);if(C){x=`rgba(34, 34, 34, ${a})`;let m=`rgba(204, 204, 204, ${a})`;l.aV&&(m=x=l.aV);let t=B.Hi/16/2,N=Math.max(t,1);var q=Math.max(2*t,1),R=Math.max(3*t,1);let W=Math.max(5*t,1);a=[];switch(C){case 4:for(;R<=W;R+=t)a.push(`${q}px ${q}px ${R}px ${x}`);break;case 1:q=window.devicePixelRatio>=2?.5:1;for(C=N;C<=R;C+=q)a.push(`${C}px ${C}px ${x}`);break;case 2:a.push(`${N}px ${N}px ${m}`);a.push(`-${N}px -${N}px ${x}`);break;case 3:for(R=0;R<
5;R++)a.push(`0 0 ${q}px ${x}`)}p["text-shadow"]=a.join(", ")}x="";switch(l.fontFamily){case 1:x='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:x='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:x='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:x='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:x='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';
break;case 7:x=g.$a()?'"Carrois Gothic SC", sans-serif-smallcaps':'Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:x='"YouTube Noto", Roboto, Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}x&&(p["font-family"]=x);x=l.offset;x==null&&(x=B.W.ii.offset);switch(x){case 0:p["vertical-align"]="sub";break;case 2:p["vertical-align"]="super"}l.fontFamily===7&&(p["font-variant"]="small-caps");l.bold&&(p["font-weight"]="bold");l.italic&&(p["font-style"]="italic");l.underline&&
(p["text-decoration"]="underline");l.b2&&(p.visibility="hidden");l.W$===1&&B.V&&(p["text-combine-upright"]="all",p["text-orientation"]="mixed",x=g.SE||g.of,B.O.params.YM===3?p.transform=x?"rotate(90deg)":"rotate(180deg)":x&&(p.transform="rotate(-90deg)"));if(l.textEmphasis===1||l.textEmphasis===2||l.textEmphasis===3||l.textEmphasis===4||l.textEmphasis===5)if(g.SE)p["font-weight"]="bold";else switch(p["text-emphasis-style"]="filled circle",p["text-emphasis-color"]="currentcolor",p["webkit-text-emphasis"]=
"filled circle",l.textEmphasis){case 4:case 3:p["text-emphasis-position"]="under left";p["webkit-text-emphasis-position"]="under left";break;case 5:case 2:p["text-emphasis-position"]="over right",p["webkit-text-emphasis-position"]="over right"}return p},lpt=function(B,l){if(B.r8&&l.length===0)return 0;
B=1;for(let p=0;p<l.length;p++){let a=l[p];typeof a.text==="string"&&(B+=a.text.split("\n").length-1,a.append||p===0||B++)}return B},uL=function(B){B=B.split("px");
return B.length>0?(B=Number(B[0]))?B:0:0},xd7=function(B,l,p){B.s$=B.s$||!!p;
var a={};Object.assign(a,B.W.ii);Object.assign(a,p||l.W);Object.assign(a,B.Wk.ii);(p=!B.N)&&pJj(B);var x=B.FT&&B.g8&&g.Tv(a,B.g8)?B.FT:apx(B,a),C=typeof l.text==="string",q=C?l.text.split("\n"):[l.text];for(let m=0;m<q.length;m++){var R=m>0||!l.append;let t=q[m];R&&!p?(pJj(B),x=apx(B,a)):R&&p&&(p=!1);t&&(x.appendChild(C?g.mr(t):t),C||t.tagName!=="RUBY"||t.childElementCount!==4||g.SE||!g.vL(t.children[2],"text-emphasis")||(R=B.V?"padding-right":"padding-top",g.vL(t.children[2],"text-emphasis-position")&&
(R=B.V?"padding-left":"padding-bottom"),g.pK?g.s4(x,R,"1em"):g.s4(x,R,"0.5em")))}B.g8=a;B.FT=x;B.Z.push(l)},pJj=function(B){if(B.N){var l=B.N;
if(B.mf){var p=B.W.textAlign;p===0?(l=l.firstElementChild)&&g.s4(l,{"border-bottom-left-radius":"0"}):p===1&&(l=l.lastElementChild)&&g.s4(l,{"border-bottom-right-radius":"0"})}}B.N=g.Rg("SPAN");g.s4(B.N,{display:"block"});g.Kz(B.N,"caption-visual-line");B.G.appendChild(B.N)},apx=function(B,l){var p=g.Rg("SPAN");
g.s4(p,{display:"inline-block","white-space":"pre-wrap"});g.s4(p,BSi(B,l));p.classList.add("ytp-caption-segment");B.N.appendChild(p);B.mf&&B.G.children.length>1&&(B=B.W.textAlign,B===0?p.previousElementSibling||g.s4(p,{"border-top-left-radius":"0"}):B===1&&g.s4(p,{"border-top-right-radius":"0"}));p.previousElementSibling&&(g.s4(p.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.s4(p,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return p},
qSP=function(B,l,p){if(B===255&&l===255||!B&&!l)return{hq:B,
iS:l,result:0};B=CX7[B];l=CX7[l];if(B&128){var a;if(a=!(l&128))a=l,a=p.Qa()&&p.iS===a;if(a)return{hq:B,iS:l,result:1}}else if(l&128&&1<=B&&B<=31)return{hq:B,iS:l,result:2};return{hq:B,iS:l,result:3}},RBj=function(B,l,p,a){l===255&&p===255||!l&&!p?(++B.O===45&&B.reset(),B.D.A.clear(),B.G.A.clear()):(B.O=0,iuj(B.D,l,p,a))},mdP=function(B,l){B.W.sort((p,a)=>{var x=p.time-a.time;
return x===0?p.order-a.order:x});
for(let p of B.W)B.time=p.time,p.type===0?RBj(B,p.UN,p.eB,l):p.type===1&&B.A&496&&iuj(B.G,p.UN,p.eB,l);B.W.length=0},EBk=function(B,l){switch(B){case 0:return tZT[(l&127)-32];
case 1:return NST[l&15];case 2:return WOT[l&31];case 3:return PXP[l&31]}return 0},XU=function(B,l){if(B.style.type===3){var p=0,a=0,x=B.G.time+0,C="",q="",R=x;
for(var m=1;m<=15;++m){var t=!1;for(var N=a?a:1;N<=32;++N){var W=B.O[m][N];if(W.W!==0){p===0&&(p=m,a=N);t=String.fromCharCode(W.W);var P=W.timestamp;P<x&&(x=P);W.timestamp=R;q&&(C+=q,q="");C+=t;t=!0}if((W.W===0||N===32)&&t){q="\n";break}else if(a&&!t)break}if(p&&!t)break}C&&l.D(p,a,x,R,C)}else for(a=p=0,C=x=B.G.time+0,q=1;q<=15;++q)for(R="",m=1;m<=32;++m)if(N=B.O[q][m],W=N.W,W!==0&&(p===0&&(p=q,a=m),t=String.fromCharCode(W),P=N.timestamp,P<=x&&(x=P),R+=t,N.reset()),m===32||W===0)R&&l.D(p,a,x,C,R),
x=C,R="",a=p=0},vV=function(B){return B.O[B.row][B.A]},Ld=function(B,l,p){l>=2&&B.A>1&&(--B.A,vV(B).W=0);
var a=vV(B);a.timestamp=B.G.time+0;a.W=EBk(l,p);B.A<32&&B.A++},DdU=function(B,l,p,a){for(let q=0;q<a;q++)for(let R=0;R<=32;R++){var x=B.O[l+q][R],C=B.O[p+q][R];
x.W=C.W;x.timestamp=C.timestamp}},Gt=function(B,l,p){for(let a=0;a<p;a++)for(let x=0;x<=32;x++)B.O[l+a][x].reset()},cV=function(B){B.row=B.W>0?B.W:1;
B.A=1;Gt(B,0,15)},Jfj=function(B){B.style.set(1);
B.W=B.D;B.W.W=0;B.W.style=B.style;B.O.mode=1<<B.W.D},da=function(B,l,p){var a=B.A,x=!1;
switch(B.style.get()){case 4:case 1:case 2:B.style.get()===4&&a.W>0||(XU(a,p),cV(B.A),cV(B.D),a.row=15,a.W=l,x=!0)}B.style.set(3);B.W=a;B.W.style=B.style;B.O.mode=1<<a.D;x?a.A=1:a.W!==l&&(a.W>l?(XU(a,p),Gt(a,a.row-a.W,l)):a.row<l&&(l=a.W),a.W=l)},MZi=function(B){B.style.set(4);
B.W=B.text;B.W.style=B.style;B.O.mode=1<<B.W.D},iuj=function(B,l,p,a){B.A.update();
l=qSP(l,p,B.A);switch(l.result){case 0:return;case 1:case 2:return}var x=l.hq;l=l.iS;if(32<=x||!x)B.W.mode&B.W.A&&(p=x,p&128&&(p=127),l&128&&(l=127),B=B.D.W,p&96&&Ld(B,0,p),l&96&&Ld(B,0,l),p!==0&&l!==0&&B.style.type===3&&XU(B,a));else if(x&16)a:if(!B.A.matches(x,l)&&(p=B.A,p.hq=x,p.iS=l,p.state=2,p=x&8?B.V:B.O,B.D=p,B.W.mode=1<<(B.G<<2)+(p.G<<1)+(p.style.type===4?1:0),(B.W.mode|1<<(B.G<<2)+(p.G<<1)+(p.style.type!==4?1:0))&B.W.A))if(l&64){a=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(x&7)<<1|l>>5&1];
B=l&16?((l&14)>>1)*4:0;l=p.W;switch(p.style.get()){case 4:a=l.row;break;case 3:if(a!==l.row){if(a<l.W&&(a=l.W,a===l.row))break;var C=1+l.row-l.W;let q=1+a-l.W;DdU(l,q,C,l.W);p=C;x=l.W;q<C?(C=q+x-C,C>0&&(p+=C,x-=C)):(C=C+x-q,C>0&&(x-=C));Gt(l,p,x)}}l.row=a;l.A=B+1}else switch(x&7){case 1:switch(l&112){case 32:Ld(p.W,0,32);break a;case 48:l===57?(a=p.W,vV(a).W=0,a.A<32&&a.A++):Ld(p.W,1,l&15)}break;case 2:l&32&&Ld(p.W,2,l&31);break;case 3:l&32&&Ld(p.W,3,l&31);break;case 4:case 5:if(32<=l&&l<=47)switch(l){case 32:Jfj(p);
break;case 33:a=p.W;a.A>1&&(--a.A,vV(a).W=0);break;case 36:a=p.W;B=vV(a);for(l=0;l<=15;l++)for(p=0;p<=32;p++)if(a.O[l][p]===B){for(;p<=32;p++)a.O[l][p].reset();break}break;case 37:da(p,2,a);break;case 38:da(p,3,a);break;case 39:da(p,4,a);break;case 40:Ld(p.W,0,32);break;case 41:a=p;a.style.set(2);a.W=a.A;a.W.W=0;a.W.style=a.style;a.O.mode=1<<a.W.D;break;case 42:a=p;B=a.text;B.W=15;B.style.set(4);cV(B);MZi(a);break;case 43:MZi(p);break;case 44:B=p;l=B.A;switch(B.style.get()){case 1:case 2:case 3:XU(l,
a)}Gt(l,0,15);break;case 45:b:{l=p;B=l.W;switch(l.style.get()){default:case 2:case 1:break b;case 4:if(B.row<15){++B.row;B.A=1;break b}break;case 3:}B.W<2&&(B.W=2,B.row<B.W&&(B.row=B.W));l=B.row-B.W+1;XU(B,a);DdU(B,l,l+1,B.W-1);Gt(B,B.row,1)}break;case 46:Gt(p.D,0,15);break;case 47:B=p,XU(B.A,a),B.D.updateTime(B.O.time+0),a=B.D,B.D=B.A,B.A=a,Jfj(B)}break;case 7:switch(l){case 33:case 34:case 35:a=p.W,(a.A+=l&3)>32&&(a.A=32)}}},zBn=function(B,l,p,a,x,C,q){var R=C[0],m=q[R.getAttribute("p")];
if(m.Ew===1){var t=C[1],N=C[2];C=C[3];R.getAttribute("t");t.getAttribute("t");N.getAttribute("t");C.getAttribute("t");R.getAttribute("p");t.getAttribute("p");C.getAttribute("p");q=q[N.getAttribute("p")];R=Huj(R.textContent,t.textContent,N.textContent,C.textContent,q);return new Vd(B,l,x,p,R,a,m)}switch(m.Ew){case 9:case 10:m.textEmphasis=1;break;case 11:m.textEmphasis=2;break;case 12:m.textEmphasis=3;break;case 13:m.textEmphasis=4;break;case 14:m.textEmphasis=5}return new Vd(B,l,x,p,R.textContent||
"",a,m)},Huj=function(B,l,p,a,x){var C=g.$a(),q=C?g.Rg("DIV"):g.Rg("RUBY"),R=g.Rg("SPAN");
R.textContent=B;q.appendChild(R);B=C?g.Rg("DIV"):g.Rg("RP");B.textContent=l;q.appendChild(B);l=C?g.Rg("DIV"):g.Rg("RT");l.textContent=p;q.appendChild(l);p=x.Ew;if(p===10||p===11||p===12||p===13||p===14)if(g.s4(l,"text-emphasis-style","filled circle"),g.s4(l,"text-emphasis-color","currentcolor"),g.s4(l,"webkit-text-emphasis","filled circle"),x.Ew===11||x.Ew===13)g.s4(l,"webkit-text-emphasis-position","under left"),g.s4(l,"text-emphasis-position","under left");p=!0;if(x.Ew===4||x.Ew===7||x.Ew===12||
x.Ew===14)g.s4(q,"ruby-position","over"),g.s4(q,"-webkit-ruby-position","before");else if(x.Ew===5||x.Ew===6||x.Ew===11||x.Ew===13)g.s4(q,"ruby-position","under"),g.s4(q,"-webkit-ruby-position","after"),p=!1;x=C?g.Rg("DIV"):g.Rg("RP");x.textContent=a;q.appendChild(x);C&&(a=p,g.s4(q,{display:"inline-block",position:"relative"}),C=q.firstElementChild.nextElementSibling,g.s4(C,"display","none"),C=C.nextElementSibling,g.s4(C,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.s4(q.lastElementChild,"display","none"),a?(g.s4(q,"padding-top","0.6em"),g.s4(C,"top","0")):(g.s4(q,"padding-bottom","0.6em"),g.s4(C,"bottom","0")));return q},bup=function(B){var l="_"+Z3++;
return new SF(0,0x8000000000000,0,l,B)},jF=function(B,l){B=B.getAttribute(l);
if(B!=null)return Number(B)},Is=function(B,l){B=B.getAttribute(l);
if(B!=null)return B==="1"},OR=function(B,l){B=jF(B,l);
return B!==void 0?B:null},wa=function(B,l){B=B.getAttribute(l);
if(B!=null)return Tt.test(B),B},oBl=function(B,l){var p={},a=l.getAttribute("ws");
Object.assign(p,a?B.Z[a]:B.D);B=OR(l,"mh");B!=null&&(p.yV=B);B=OR(l,"ju");B!=null&&(p.textAlign=B);B=OR(l,"pd");B!=null&&(p.YM=B);B=OR(l,"sd");B!=null&&(p.f$=B);B=wa(l,"wfc");B!=null&&(p.windowColor=B);l=jF(l,"wfo");l!==void 0&&(p.windowOpacity=l/255);return p},FOn=function(B,l){var p={},a=l.getAttribute("wp");
a&&Object.assign(p,B.L[a]);B=OR(l,"ap");B!=null&&(p.cj=B);B=jF(l,"cc");B!=null&&(p.Ro=B);B=jF(l,"ah");B!=null&&(p.TU=B);B=jF(l,"rc");B!=null&&(p.ZV=B);l=jF(l,"av");l!=null&&(p.tN=l);return p},hBU=function(B,l,p,a){var x={};
Object.assign(x,FOn(B,l));Object.assign(x,oBl(B,l));a?g.Tv(x,B.D)?(a=B.G,x=B.D):a="_"+Z3++:a=l.getAttribute("id")||"_"+Z3++;B=jF(l,"t")+p;l=jF(l,"d")||0x8000000000000;if(x.YM===2||x.YM===3)p=x.ZV,x.ZV=x.Ro,x.Ro=p;return new SF(B,l,0,a,x)},eF=function(B){B=g.Jl(Math.round(B),0,16777215).toString(16).toUpperCase();
return"#000000".substring(0,7-B.length)+B},s5b=function(B,l,p,a,x){a===0&&(a=0x8000000000000);
var C={};l.wpWinPosId&&Object.assign(C,B.D.get(l.wpWinPosId));l.wsWinStyleId&&Object.assign(C,B.G.get(l.wsWinStyleId));B=l.rcRowCount;B!==void 0&&(C.ZV=B);l=l.ccColCount;l!==void 0&&(C.Ro=l);if(C.YM===2||C.YM===3)l=C.ZV,C.ZV=C.Ro,C.Ro=l;return new SF(p,a,0,x,C)},Ap=function(B){var l=B.byteOffset;
B.byteOffset+=1;return B.W.getUint8(l)},$x=function(B){var l=B.byteOffset;
B.byteOffset+=4;return B.W.getUint32(l)},XJE=function(B){if(typeof B==="string")return!1;
B=new kPl(B,0);return uWl(B)},uWl=function(B){if(!(B.byteOffset<B.W.byteLength)||$x(B)!==1380139777)return!1;
B.version=Ap(B);if(B.version>1)return!1;Ap(B);Ap(B);Ap(B);return!0},vBt=function(B,l){if(!l)return"";
B.V&&B.O.params.f$!==1&&(l*=-1);return`translate${B.V?"X":"Y"}(${l}px)`},LOb=function(B){B.kh=Array.from(B.element.getElementsByClassName("caption-visual-line"));
for(var l=B.O.params.ZV,p=0,a=0,x=B.kh.length-1;p<l&&x>-1;){var C=B.kh[x];a+=B.V?C.offsetWidth:C.offsetHeight;p++;x--}B.uH=a;l=Math;p=l.max;isNaN(B.Nc)&&((a=B.W.Ro)?(x=g.Rg("SPAN"),g.E6(x,"\u2013".repeat(a)),g.s4(x,BSi(B,B.W.ii)),B.G.appendChild(x),B.Nc=x.offsetWidth,B.G.removeChild(x)):B.Nc=0);a=B.G;B.DB=p.call(l,B.Nc,B.jm,(B.V?a.offsetHeight:a.offsetWidth)+1)},GPT=function(B,l){LOb(B);
var p=B.kh.reduce((a,x)=>(B.V?x.offsetWidth:x.offsetHeight)+a,0);
p=B.uH-p;if(p!==B.Kj){let a=p>0&&B.Kj===0,x=p<B.Kj;l||isNaN(p)||a||!x||(g.Kz(B.element,"ytp-rollup-mode"),B.Wi(B.element,"transitionend",B.Om));g.s4(B.G,"transform",vBt(B,p));B.Kj=p}LOb(B)},ddU=function(B,l,p,a){var {formatId:x,
zo:C,startTimeMs:q,durationMs:R}=B.G(l),m={formatId:x,startTimeMs:q,durationMs:R,zU:C,zm:C},t=cfk(B.nA,m.startTimeMs),N=t>=0?B.nA[t]:null,W=N?N.startTimeMs+N.durationMs:0,P=m.startTimeMs+m.durationMs;!N||m.startTimeMs-W>B.D?B.nA.splice(t+1,0,m):(N.durationMs=Math.max(W,P)-N.startTimeMs,N.zm=Math.max(N.zm,m.zm));a(B.nA);a=g.Fe(l);B=B.V;a=a.buffer.slice(a.byteOffset,a.byteLength+a.byteOffset);l=l.info.O;B.J?B.L==null?g.HR(B.logger,350058965,"Null loaded track meta data at captions data received"):p.Qo(a,
B.L,l*1E3):g.HR(B.logger,350058965,"Null Representation at captions data received")},SS7=function(B,l){B.A=(p,a)=>{if(B.B.Y().experiments.U$("html5_sabr_live_support_subfragmented_captions"))(B.W?B.W=B.W.G(p):(B.W=p,VZE(B.W)),B.W)?p.info.Qf&&(Zun(B.W),ddU(B,B.W,l,a),B.W=null):g.HR(B.logger,350058965,"Empty slice");
else if(p.info.Qf){var x=p;if(B.xC.length>0){for(x=B.xC.shift();B.xC.length>0;)x=x.G(B.xC.shift());x=x.G(p)}x?(VZE(x),Zun(x),ddU(B,x,l,a)):g.HR(B.logger,350058965,"Empty slice")}else B.xC.push(p)};
B.B.addEventListener("sabrCaptionsDataLoaded",B.A)},cfk=function(B,l){B=g.ro(B,{startTimeMs:l},(p,a)=>p.startTimeMs-a.startTimeMs);
return B>=0?B:-B-2},VZE=function(B){try{var l=g.uP(B)*1E3}catch(p){l=B.info.startTime*1E3}l<0&&(l=B.info.startTime*1E3);
B.info.startTime=l/1E3;B.info.O=l/1E3},Zun=function(B){try{var l=g.cR(B)*1E3}catch(p){l=B.info.duration*1E3}l<0&&(l=B.info.duration*1E3);
B.info.duration=l/1E3;B.info.N=l/1E3},j5B=function(B,l){if(!g.lo(B)||B.W!=null&&g.UU(l,B.W)&&B.W.W.rawcc!=null)return!1;
l=!!B.W&&B.W.isManifestless&&Object.values(B.W.W).some(p=>g.re(p,"386"));
B=!!B.W&&!B.W.isManifestless&&g.YF(B.W);return l||B},gBl=function(B,l,p){var a=[];
for(let x in B.A.W){if(!B.A.W.hasOwnProperty(x))continue;let C=B.A.W[x];if(g.re(C,p||null)){let q=C.info.captionTrack;q&&q.languageCode===l&&a.push(C)}}return a.length?a[0]:null},Ipk=function(B,l){var p=[];
for(let x in B.A.W){if(!B.A.W.hasOwnProperty(x))continue;var a=B.A.W[x];if(g.re(a,l||null)){let C=a.info.id,q=C,R=`.${C}`,m="",t="";if(a=a.info.captionTrack)C=a.languageCode,q=a.displayName,R=a.vssId,m=a.kind,t=a.id;p.push(new g.JY({id:x,languageCode:C,languageName:q,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:R,kind:m,captionId:t}))}}return p},TSP=function(B){var l=Oul.length;
if(B.byteLength<l)return!1;B=new Uint8Array(B,0,l);for(let p=0;p<l;p++)if(Oul[p]!==B[p])return!1;return!0},Qd=function(B){B=B.split(":");
var l=0;for(let p of B)l=l*60+Number(p);return l*1E3},wJx=function(B,l,p,a){a=Object.assign({yV:0},a);
return new SF(B,l,p,"_"+Z3++,a)},eBn=function(B,l,p,a,x,C,q,R,m){switch(q.tagName){case "b":R.bold=!0;
break;case "i":R.italic=!0;break;case "u":R.underline=!0}for(let N=0;N<q.childNodes.length;N++){var t=q.childNodes[N];if(t.nodeType===3)t=new Vd(l,p,a,x.id,t.nodeValue,C||N>0,g.gY(R)?void 0:R),m.push(t),x.W.push(t);else{let W={};Object.assign(W,R);eBn(B,l,p,a,x,!0,t,W,m)}}},$dt=function(B,l,p){if(typeof l==="string"||XJE(l))return[{trackData:l,
Fr:p}];if(typeof l==="string"&&l.substring(0,6)==="WEBVTT"||typeof l!=="string"&&TSP(l))return[{trackData:l,Fr:p}];var a=new DataView(l);if(a.byteLength<=8||a.getUint32(4)!==1718909296)return[];var x=g.BX(a);if(B.QF&&x){var C=g.ZK(x),q=g.Sn(x);x=x.segmentNumber;C&&x&&B.QF.I$(x,C,q)}B=g.yT(a,1835295092);if(!B||!B.length||!B[0].size)return[];C=[];for(q=0;q<B.length;q++)x=B[q],x=new Uint8Array(l,x.dataOffset,x.size-(x.dataOffset-x.offset)),x=g.ki(x),C.push({trackData:x,Fr:p+q*1E3});AfU(a,C,p);return C=
C.filter(R=>!!R.trackData)},fpE=function(B,l,p){B.W||(B.W=new Q5l);
B=B.W.O(l,p);Math.random()<.01&&g.Mh(Error("Deprecated subtitles format in web player: WebVTT"));return B},AfU=function(B,l,p){var a=g.wr(B,0,1836476516),x=9E4;
a&&(x=g.$l(a)||9E4);a=0;var C=g.yT(B,1836019558);for(let R=0;R<C.length;R++){var q=C[R];R<l.length&&(q=g.wr(B,q.dataOffset,1953653094))&&(q=g.wr(B,q.dataOffset,1952867444))&&(q=g.Kv(q)/x*1E3,R===0&&(a=q),l[R].Fr=q-a+p||p*R*1E3)}},YSj=function(B){var l={};
if(B=g.nV(B))l.lang=B,g.s6t.test(B)&&(l.YM=1);return l},fd=function(B){return B.O==="HLS"&&B.j1?!0:B.s$&&B.j1&&B.O!=="LIVE"&&B.O!=="SABR_LIVE"},KOW=function(B){return!B.D&&B.s$&&B.r8&&(B.O==="LIVE"||B.O==="SABR_LIVE")},Yx=function(B,l,p=!1){var a=B.X.S("enable_player_captions_new_style_defaults")?nBk:yfn,x=a.ii;
B.G={};Object.assign(B.G,a);B.G.ii={};Object.assign(B.G.ii,x);B.V={ii:{}};var C=l.backgroundOverride?B.V:B.G,q=l.background||x.background;Tt.test(q);C.ii.background=q;C=l.colorOverride?B.V:B.G;q=l.color||x.color;Tt.test(q);C.ii.color=q;C=l.windowColorOverride?B.V:B.G;q=l.windowColor||a.windowColor;Tt.test(q);C.windowColor=q;C=l.backgroundOpacityOverride?B.V:B.G;q=l.backgroundOpacity;q==null&&(q=x.backgroundOpacity);C.ii.backgroundOpacity=q;C=l.fontSizeIncrementOverride?B.V:B.G;q=l.fontSizeIncrement;
q==null&&(q=x.fontSizeIncrement);C.ii.fontSizeIncrement=q;q=l.fontStyleOverride?B.V:B.G;C=l.fontStyle;C==null&&(C=x.bold&&x.italic?3:x.bold?1:x.italic?2:0);q=q.ii;switch(C){case 1:q.bold=!0;delete q.italic;break;case 2:delete q.bold;q.italic=!0;break;case 3:q.bold=!0;q.italic=!0;break;default:delete q.bold,delete q.italic}C=l.textOpacityOverride?B.V:B.G;q=l.textOpacity;q==null&&(q=x.textOpacity);C.ii.textOpacity=q;C=l.windowOpacityOverride?B.V:B.G;q=l.windowOpacity;q==null&&(q=a.windowOpacity);C.windowOpacity=
q;a=l.charEdgeStyleOverride?B.V:B.G;C=l.charEdgeStyle;C==null&&(C=x.charEdgeStyle);a.ii.charEdgeStyle=C;a=l.fontFamilyOverride?B.V:B.G;C=l.fontFamily;C==null&&(C=x.fontFamily);a.ii.fontFamily=C;B.loaded&&B.Jm();p&&g.gz("yt-player-caption-display-settings",l,2592E3)},Kd=function(B,l,p){l&&!B.U?(l=bup({YM:0,
lang:"en-GB"}),B.U=[l,new Vd(l.start,l.end-l.start,0,l.id,p??"Captions look like this")],B.player.AB(B.U)):!l&&B.U&&(Udk(B,B.U),B.U=null)},BJn=function(B){if(B.X.S("enable_player_captions_persistence_state_machine")){var l=g.IG("yt-player-caption-persistence");
if(l==null){let p=g.$0().QY(65);if(p===!0)l=!1;else{let a=g.Lk(B.X)?nd(B):rfx(B);a!=null?l=!!a:p===!1&&(l=!0)}l!==void 0&&yd(B,l)}return l}},nd=function(B){if(!B.B.isInline())return g.IG("yt-player-sticky-caption")},rfx=function(B){if(!B.storage)return null;
try{var l=B.storage.get("module-enabled")}catch(p){B.storage.remove("module-enabled")}return l},UR=function(B){if(B.X.S("enable_player_captions_persistence_state_machine"))return BJn(B);
var l=void 0,p=g.$0().QY(65);if(g.Lk(B.X)&&p!=null){if(nd(B)!=null)return!1;l=!p}return l},l1t=function(B){if(B.X.XZ===1||B.videoData.Pe===1||g.AV(B.videoData,"yt:cc")==="alwayson")return!0;
if(B.videoData.captionTracks.length)var l=B.getAudioTrack().A;if(B.X.S("enable_player_captions_persistence_state_machine")){var p=BJn(B);if(p!==void 0)return!!p}else if(B.X.XZ===2&&(g.Lk(B.X)?p=nd(B):p=rfx(B),p!=null))return!!p;p=os(B.player.getAudioTrack(),g.Lk(B.X));var a=g.AV(B.videoData,"yt:cc");if(UR(B)===void 0){if(p==="CAPTIONS_INITIAL_STATE_ON_RECOMMENDED")return a?a==="on":!0;if(p==="CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED")return a==="on"}else return a==="on";return l==="ON"||g.AV(B.videoData,
"yt:cc")==="on"},ra=function(B,l=!1){if(B.A&&!l||!B.videoData.captionTracks.length)return!1;
B=B.getAudioTrack();return!!B.W||B.A==="FORCED_ON"},pKl=function(B){return B.X.S("html5_honor_caption_availabilities_in_audio_track")&&B.O!=="LIVE"&&B.O!=="SABR_LIVE"},a1b=function(B,l){if(B.A){var p=B.B.LA().mq().textTracks,a=null;
B.O==="HLS"?a=B.A.getId():a=B.A.toString();for(let C=0;C<p.length;C++){var x=p[C];x.id===a&&(l?x.mode!=="showing"&&(x.mode="showing",x=B.A,B.XV(x,!!x,BQ(B)?"g":B.L?"m":"s")):x.mode==="showing"&&(x.mode="disabled"))}}},BQ=function(B){var l=lh(B);
return!!l&&B.A===l},xjp=function(B,l){if(B.O==="HLS")return!1;
g.Uw(B.videoData)&&(l=!0);l||(l=B.O==="TTS"?!1:B.O==="INNERTUBE"?!1:!0);return l||B.X.S("web_watch_disable_account_level_captions_settings")&&g.Lk(B.X)?!0:!!g.$0().QY(66)},lh=function(B){return B.Z&&B.Z.W},ps=function(B,l){if(!B.W)return null;
if(B.Z&&B.Z.D)return B.Z.D;l=xjp(B,l);l=B.W.W.W(l);var p=null;if(jbt(B.X)){var a=B.B.isInline()?void 0:g.IG("yt-player-caption-sticky-language");var x=[a,B.videoData.captionsLanguagePreference,B.X.captionsLanguagePreference,g.AV(B.videoData,"yt:cc_default_lang")];let R=!1;for(let m=0;m<x.length;m++){let t=x[m];if(t){R=!0;for(var C=0;C<l.length;C++)if(g.nV(l[C])===t)return l[C];for(C=0;C<l.length;C++)if(g.nV(l[C]).split("-")[0]===t.split("-")[0])return l[C]}}if(R&&B.W&&(x=B.W.Z,x.length))for(var q of x)if(q.languageCode===
a){p=q;break}}else for(q=[B.videoData.captionsLanguagePreference,B.X.captionsLanguagePreference,g.AV(B.videoData,"yt:cc_default_lang")],a=0;a<q.length;a++)for(x=0;x<l.length;x++)if(g.nV(l[x])===q[a])return l[x];q=null;B.Z&&B.Z.O&&(q=B.Z.O);q||(q=l.find(R=>R.isDefault)||null);
q||(q=l[0]||lh(B));q&&p&&g.nV(q).split("-")[0]!==p.languageCode.split("-")[0]&&(q=Sfp(q,p));return q},q6=function(B,l,p){B.loaded&&B.unload();
p!=null&&(B.L=p,B.L&&(B.X.S("enable_player_captions_persistence_state_machine")?yd(B,!!l):g.Lk(B.X)?ap(B,!!l):xj(B,!!l)));l!==null||ra(B,!0)||B.XV(l,!!l,B.L?"m":"s");B.A=l;ra(B)&&(B.A=lh(B));Cs(B,B.A??void 0);B.load()},yd=function(B,l){B.X.S("enable_player_captions_persistence_state_machine")&&g.gz("yt-player-caption-persistence",l,3122064E3)},ap=function(B,l){B.B.isInline()||g.gz("yt-player-sticky-caption",l,2592E3)},xj=function(B,l){if(B.storage)try{B.storage.set("module-enabled",l)}catch(p){}},
Cs=function(B,l){B.X.S("html5_modify_caption_vss_logging")&&(B.videoData.X4=l)},qkl=function(B,l){var p=B.DB[l.id];
p&&p.O!==l&&(p.dispose(),delete B.DB[l.id],p=null);p||(p=CmB(B,l))&&(B.DB[l.id]=p)},irb=function(B,l){var p=l.windowId;
B.g8[p]||(B.g8[p]=[]);B.g8[p].push(l)},CmB=function(B,l){var p=REE(B);
if(!p)return null;var a=B.A?g.nV(B.A):null;a&&g.s6t.test(a)&&(l.params.YM=1);var x=B.Om.getPlayerSize();a=x.height*B.uH.height;x=x.width*B.uH.width;B.X.playerStyle!=="google-live"||B.G.isDefault||Object.assign(l.params,B.G);switch(l.params.yV!=null?l.params.yV:l.W.length>1?1:0){case 1:return new mjn(l,B.G,B.V,p.width,p.height,x,a,B.X.experiments,B.bH.bind(B),B.B);case 2:return new trk(l,B.G,B.V,p.width,p.height,x,a,B.X.experiments,B.bH.bind(B),B.B);default:return new ih(l,B.G,B.V,p.width,p.height,
x,a,B.X.experiments,B.bH.bind(B),B.B)}},REE=function(B){var l=B.Om.getVideoContentRect(!0).height,p=B.Om.getVideoContentRect(!0).width;
if(!l||!p)return null;l*=B.uH.height;p*=B.uH.width;return{width:p,height:l}},Udk=function(B,l){B.player.JC(l);
for(let p of l)g.$S(B.kh,p);zt(B.Nc)},NJE=function(B,l){if(!B.W)return{};
if(l){g.gY(l)||B.w6(l.vss_id,"m");if(B.D&&B.O!=="HLS"||!g.hE(l))return;if(g.gY(l)){q6(B,null,!0);return}let a;var p=B.W.W.W(!0);for(let x=0;x<p.length;x++){let C=p[x];C.languageCode!==l.languageCode||a&&(C.languageName!==l.languageName||(C.captionId||"")!==(l.captionId||"")||g.KV(C)!==l.displayName)||(a=l.translationLanguage?Sfp(C,l.translationLanguage):C)}B.M3(l.position);!a||a===B.A&&B.loaded||(l=g.v7(),p=g.nV(a),l.length&&p===l[l.length-1]||(l.push(p),g.gz("yt-player-caption-language-preferences",
l)),jbt(B.X)&&!B.B.isInline()&&g.gz("yt-player-caption-sticky-language",p,2592E3),q6(B,a,!0))}else return B.loaded&&B.A&&!BQ(B)?bL(B.A):{};return""};
g.v0.prototype.I$=g.Cn(120,function(B,l,p){this.A.set(B,{jO:l,df:p})});
g.L7.prototype.I$=g.Cn(119,function(B,l,p){this.Cj.I$(B,l,p)});
g.LM.prototype.L=g.Cn(118,function(){this.mediaElement.L()});
g.kQ.prototype.L=g.Cn(117,function(){var B=g.Ul(document,"track",void 0,this.W);for(let l=0;l<B.length;l++)g.Wq(B[l])});
g.LM.prototype.s$=g.Cn(116,function(){return this.mediaElement.s$()});
g.kQ.prototype.s$=g.Cn(115,function(){return!(!this.W.textTracks||!this.W.textTracks.addEventListener)});
g.LM.prototype.Nc=g.Cn(114,function(){return this.mediaElement.Nc()});
g.kQ.prototype.Nc=g.Cn(113,function(){return!!this.W.textTracks});
g.LM.prototype.uH=g.Cn(112,function(B){this.mediaElement.uH(B)});
g.kQ.prototype.uH=g.Cn(111,function(B){for(let l=0;l<B.length;l++)this.W.appendChild(B[l])});
g.p7.prototype.w6=g.Cn(47,function(B,l){this.app.lH().w6(B,l)});
g.rR.prototype.w6=g.Cn(46,function(B,l){this.C.w6(B,l)});
g.DU.prototype.w6=g.Cn(45,function(B,l){B=[B,l];g.lt(this,g.aN(this.provider),"cfi",B)});
g.z3.prototype.w6=g.Cn(44,function(B,l){this.qoe&&this.qoe.w6(B,l)});
g.UZ.prototype.w6=g.Cn(43,function(B,l){this.Ya.w6(B,l)});
g.k$.prototype.w6=g.Cn(42,function(){});
g.p7.prototype.XV=g.Cn(41,function(B,l,p){this.app.lH().XV(B,l,p)});
g.rR.prototype.XV=g.Cn(40,function(B,l,p){this.C.XV(B,l,p)});
g.DU.prototype.XV=g.Cn(39,function(B,l,p){if(this.mf!==B||this.vO!==l)l=l==="rawcc"?"":l,p=[B,l,this.mf,p],g.lt(this,g.aN(this.provider),"cfs",p),this.mf=B,this.vO=l});
g.z3.prototype.XV=g.Cn(38,function(B,l,p){this.qoe&&this.qoe.XV(B,l,p)});
g.UZ.prototype.XV=g.Cn(37,function(B,l,p){this.Ya.XV(B,l,p)});
g.k$.prototype.XV=g.Cn(36,function(){});
g.Mq.prototype.xc=g.Cn(10,function(){return this.QF});
g.dG.prototype.xc=g.Cn(9,function(){return this.lH().N5()});
g.p7.prototype.N5=g.Cn(8,function(){return this.app.xc()});
g.rR.prototype.N5=g.Cn(7,function(){return this.C.N5()});
g.UZ.prototype.N5=g.Cn(6,function(){return this.loader?.xc()||null});
g.k$.prototype.N5=g.Cn(5,function(){return null});
g.eG.prototype.pF=g.Cn(3,function(B){return(B=this.O(B))?B.W:0});
g.$L.prototype.pF=g.Cn(2,function(){return 0});
var Tfk=/#(.)(.)(.)/,Owl=/^#(?:[0-9a-f]{3}){1,2}$/i,Wqx=class{constructor(){this.O=[];this.A=[]}W(B){return B?this.A.concat(this.O):this.A}},Rp=class extends g.OT{constructor(B){super();this.xh=B;this.W=new Wqx;this.DB=new Wqx;this.G=null;this.Z=[];this.uH=[]}N(){}D(){}O(){}V(){return""}Cj(){return!1}GU(B,l){if(this.xh.Y().S("html5_dispatch_tracklist_loaded_event")){this.G&&(this.G.reject(),this.G=null);var p=[];this.xh.hm("trackListLoaded",this.W,p,l);this.xh.Y().S("enable_po_decoration_of_forced_tracks")&&
this.xh.hm("trackListLoaded",this.DB,p,l);p.length?(l=new g.Ko,l.promise.then(B.GU,()=>{}),this.G=l,Promise.all(p).then(l.resolve,l.reject).finally(()=>{this.G=null})):B.GU()}else B.GU()}VY(){this.G&&(this.G.reject(),this.G=null);
this.O();super.VY()}},Pmb={en:"English"},Ekn=class extends Rp{constructor(B){super(B);this.A=new Set}D(B){var l=this.xh.LA();if(l&&l.mq()){l=l.mq().textTracks;for(let p of l)p.kind==="subtitles"&&!this.A.has(p.language)&&p.language&&(sR(this.W,new g.JY({languageCode:p.language,languageName:p.language,kind:p.kind,id:p.id,displayName:Pmb[p.label]||p.label,vss_id:`.${p.language}`})),this.A.add(p.language))}this.W.W().length>0&&B.GU()}},Djt=class extends Rp{constructor(B,l,p){super(B);this.videoData=
l;this.audioTrack=p;this.A=null;this.L=!1;this.Z=l.eF;this.uH=l.yR;this.L=g.Uw(l)}N(B,l,p){this.iH();l=this.V(B,l);var a=this.xh.Y().S("html5_report_captions_ctmp_qoe"),x=(0,g.Q)();this.O();A6p(this,l,{format:"RAW",onSuccess:C=>{this.A=null;if(a){var q=(C.responseText.length/1024).toFixed();let R=(0,g.Q)();this.videoData.K("capresp",{ms:R-x,kb:q})}q=C.getResponseHeader&&C.getResponseHeader("Content-Length")?Number(C.getResponseHeader("Content-Length")):0;p.Qo(C.responseText,B,void 0,void 0,q)},
onError:a?C=>{this.videoData.K("capfail",{status:C?.status??0})}:void 0,
withCredentials:!0})}D(B){if(this.audioTrack){for(let l of this.audioTrack.captionTracks)sR(this.W,l);this.audioTrack.W&&sR(this.DB,this.audioTrack.W)}this.GU(B,this.videoData.videoId)}V(B,l){var p=B.n2(),a={fmt:l};if(l==="srv3"||l==="3"||l==="json3")g.$a()?Object.assign(a,{xorb:2,xobt:1,xovt:1}):Object.assign(a,{xorb:2,xobt:3,xovt:3});B.translationLanguage&&(a.tlang=g.nV(B));this.L&&(a.xosf="1");Object.assign(a,this.xh.Y().W);return g.yh(p,a)}O(){this.A&&this.A.abort()}},JgP=class{constructor(){this.segments=
[]}contains(B){B=g.ro(this.segments,B);return B>=0||B<0&&(-B-1)%2===1}length(){return this.segments.length/2}},MrB=class extends g.OT{constructor(B,l,p,a,x,C){super();this.policy=B;this.player=l;this.nj=p;this.L=a;this.G=x;this.J=C;this.D=new JgP;this.V=-1;this.A=this.O=this.W=null;this.uH=0;this.N=new g.wL(this.Z,1E3,this);this.events=new g.Q8(this);g.c(this,this.N);g.c(this,this.events);this.events.Wi(l,"SEEK_COMPLETE",this.U);this.U();this.Z()}VY(){super.VY();this.A&&this.A.cancel()}U(){this.seekTo(this.player.getCurrentTime())}seekTo(B){B-=
this.player.gd();var l=this.W;this.W=g.GO(this.nj.V(B).w8);l!==this.W&&this.J&&this.J()}reset(){this.D=new JgP;this.V=-1;this.A&&(this.A.cancel(),this.A=null)}Z(){this.iH();var B;if(B=this.W!=null)B=this.W,B=B.nj.D(B);if(B&&!this.A&&!(this.W&&this.W.startTime-this.player.getCurrentTime()>30)){B=this.W;B=B.nj.Nc(B);let x=B.w8[0];if(this.player.getVideoData()?.enableServerStitchedDai){var l=this.player.N5();if(l){var p=x.nj.info.id;let C=x.zo;var a=B.w8[0].O;if(this.policy.kh){if(l=g.YY(l,a,C,p,3))B.D=
l}else if(p=l.mI(a,C,p,3))if(a=2,l.AZ.has(C)?a=0:g.UG(l,C)&&(a=1),l=a,l===0)p&&(B.W=new g.kM(p));else if(l===2){this.N.start();QbP(this)&&this.seekTo(this.player.getCurrentTime());return}}}x.nj.index.Ps(x.zo)?(this.D.contains(B.w8[0].zo)||fkP(this,B),this.W=g.GO(B.w8)):QbP(this)&&this.seekTo(this.player.getCurrentTime())}this.N.start()}},Hrp=class extends Rp{constructor(B,l){super(l);this.A=B;this.B=l;this.L=null;this.U=!1;this.logger=new g.Me("caps");this.J=g.UU(this.B,this.A)}N(B,l,p){this.O();
l=YfE(this,B.getId());l||(l=B.languageCode,l=this.A.isManifestless?KPP(this,l,"386"):KPP(this,l));if(l){var a=(l.index.pF(l.index.Vy())-l.index.getStartTime(l.index.Vy()))*1E3,x=new g.DJP(this.B.Y());this.L=new MrB(x,this.B,l,(C,q)=>{p.Qo(C,B,q,a)},this.J||g.oV(l.info),()=>{this.L&&this.L.reset();
this.U=!0})}}Cj(){var B=this.U;
this.U=!1;return B}D(B){var l=this.B.Y().S("html5_fallback_if_rawcc_missing");var p=this.A.W.rawcc!=null;if(!this.J||!p&&l)l=this.A.isManifestless?ng7(this,"386"):ng7(this);else{if(!p){g.HR(this.logger,386248249,"rawcc used but unavailable");return}l=[new g.JY({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.JY({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]}for(let a of l)sR(this.W,
a);B.GU()}O(){this.L&&(this.L.dispose(),this.L=null)}V(){return""}},zEj=class extends Rp{constructor(B,l,p,a,x,C){super(B);this.videoId=p;this.U=x;this.eventId=C;this.J={};this.A=null;B=a||g.K6(l).hl||"";B=B.split("_").join("-");this.L=g.yh(l,{hl:B})}N(B,l,p){this.iH();l=this.V(B,l);this.O();this.A=g.Hf(l,{format:"RAW",onSuccess:a=>{this.A=null;var x=a.getResponseHeader&&a.getResponseHeader("Content-Length")?Number(a.getResponseHeader("Content-Length")):0;p.Qo(a.responseText,B,void 0,void 0,x)},
withCredentials:!0})}D(B){var l=this.L,p={type:"list",tlangs:1,v:this.videoId,vssids:1};this.U&&(p.asrs=1);l=g.yh(l,p);this.O();this.A=g.Hf(l,{format:"RAW",onSuccess:a=>{this.A=null;if((a=a.responseXML)&&a.firstChild){var x=a.getElementsByTagName("track");for(var C=0;C<x.length;C++){var q=x[C],R=q.getAttribute("lang_code");let m=q.getAttribute("lang_translated"),t=q.getAttribute("name"),N=q.getAttribute("kind"),W=q.getAttribute("id"),P=q.getAttribute("lang_default")==="true",E=q.getAttribute("cantran")===
"true";q=q.getAttribute("vss_id");sR(this.W,new g.JY({languageCode:R,languageName:m,name:t,kind:N,id:W,is_servable:!0,is_translateable:E,vss_id:q,is_default:P}))}a=a.getElementsByTagName("target");x=a.length;for(C=0;C<x;C++)R={languageCode:a[C].getAttribute("lang_code"),languageName:a[C].getAttribute("lang_translated"),languageOriginal:a[C].getAttribute("lang_original"),id:a[C].getAttribute("id"),isDefault:a[C].getAttribute("lang_default")==="true"},this.J[R.languageCode]=R.languageName,this.Z.push(R)}this.GU(B,
this.videoId)},
withCredentials:!0})}V(B,l){var p=this.L;l={v:this.videoId,type:"track",lang:B.languageCode,name:B.getName(),kind:B.kind,fmt:l};var a=this.xh.Y();a.S("captions_url_add_ei")&&(l.ei=this.eventId);B.translationLanguage&&(l.tlang=g.nV(B));Object.assign(l,a.W);return p=g.yh(p,l)}O(){this.A&&this.A.abort()}},Tt=/^#(?:[0-9a-f]{3}){1,2}$/i;var brT=["left","right","center","justify"];var Vd=class extends g.J3{constructor(B,l,p,a,x,C=!1,q=null){super(B,B+l,{priority:p,namespace:"captions"});this.windowId=a;this.text=x;this.append=C;this.W=q}toString(){return super.toString()}};var ih=class extends g.zE{constructor(B,l,p,a,x,C,q,R,m,t){var N=t.isInline()&&!0,W={};Object.assign(W,l);Object.assign(W,B.params);Object.assign(W,p);var P={};Object.assign(P,l.ii);B.params.ii&&Object.assign(P,B.params.ii);Object.assign(P,p.ii);N&&(W.windowOpacity=.6,P.backgroundOpacity=0);W.ii=P;var E=W.YM===1,k=[{j:"span",O$:"captions-text",fj:{style:"word-wrap: normal; display: block;"}}],G=R.U$("caption_edit_on_hover")&&t.getVideoData().getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.openTranscriptCommand;
G&&k.unshift({j:"button",O$:"caption-edit",fj:{tabindex:"0","aria-label":wET()},Lj:[{j:"svg",fj:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},Lj:[{j:"path",fj:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});super({j:"div",O$:"caption-window",fj:{id:`caption-window-${B.id}`,dir:E?"rtl":"ltr",tabindex:"0",lang:W.lang},Lj:k});
this.experiments=R;this.Z=[];this.s$=!1;this.O=B;this.g8=this.FT=null;this.o4=C;this.pv=q;this.N=null;this.maxWidth=C*.96;this.maxHeight=q*.96;this.W=W;this.Wk=p;this.Cj=l;this.G=this.Yh("captions-text");B=this.G.style;this.mf=R.U$("enable_player_captions_new_style_defaults")&&("boxDecorationBreak"in B||"WebkitBoxDecorationBreak"in B);this.Hi=y6W(a,x,C,q);this.b9=m;G&&(this.L=this.Yh("caption-edit"),this.Wi(this.L,"click",()=>{this.b9()}));
this.type=0;this.bH=this.Hi*U8W(P);this.lR=N;this.r8=R.U$("enable_centered_caption_for_tvfilm_video")&&t.getVideoData().isTvfilmVideo;this.J=t.Y().Mc().W.QY(g.ohj);a=new g.o9(this.element,!0);g.c(this,a);a.subscribe("dragstart",this.MG,this);a.subscribe("dragmove",this.JE,this);a.subscribe("dragend",this.ZD,this);this.ot=this.j1=this.tg=this.sm=0;a="";this.W.windowOpacity&&(a=FU(this.W.windowColor),a="rgba("+a[0]+","+a[1]+","+a[2]+","+this.W.windowOpacity+")");x={"background-color":a,display:this.W.isVisible===
!1?"none":"","text-align":brT[this.W.textAlign]};this.mf&&(x["border-radius"]=a?`${this.bH*.375}px`:"");(this.V=this.O.params.YM===2||this.O.params.YM===3)&&r6P(this,this.element);g.s4(this.element,x);N&&this.element.parentElement?.style.setProperty("--caption-window-color",a);switch(this.W.cj){case 0:case 1:case 2:g.Kz(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.Kz(this.element,"ytp-caption-window-bottom")}}MG(B,l){this.j1=B;this.ot=l;var p=g.V9(this.element,this.element.parentElement);
this.sm=B-p.x;this.tg=l-p.y}JE(B,l){if(B!==this.j1||l!==this.ot){g.Yo(this.element,"ytp-dragging")||g.Kz(this.element,"ytp-dragging");var p=g.gi(this.element);B=B-this.sm-.02*this.o4;var a=l-this.tg-.02*this.pv,x=(B+p.width/2)/this.maxWidth*3;x=Math.floor(g.Jl(x,0,2));var C=(a+p.height/2)/this.maxHeight*3;C=Math.floor(g.Jl(C,0,2));l=x+C*3;B=(B+x/2*p.width)/this.maxWidth;B=g.Jl(B,0,1)*100;p=(a+C/2*p.height)/this.maxHeight;p=g.Jl(p,0,1)*100;this.O.params.cj=l;this.O.params.tN=p;this.O.params.TU=B;this.O.params.isDefault=
!1;this.W.cj=l;this.W.tN=p;this.W.TU=B;this.W.isDefault=!1;this.Cj.cj=l;this.Cj.tN=p;this.Cj.TU=B;this.Cj.isDefault=!1;this.cO()}}ZD(){g.ys(this.element,"ytp-dragging")}cO(){this.U(this.Z)}U(B){var l=this.lR?0:Math.min(this.u9(),this.maxWidth),p=this.vO(),a=this.lR;if(a){var x=getComputedStyle(this.G.parentNode);x=uL(x.borderLeftWidth)+uL(x.borderRightWidth)+uL(x.paddingLeft)+uL(x.paddingRight)}else x=0;var C=x;x="";this.O.params.YM===3&&(x="rotate(180deg)");var q=a?`calc(96% - ${C}px)`:"96%";g.s4(this.element,
{top:0,left:0,right:"",bottom:"",width:l?`${l}px`:"",height:p?`${p}px`:"","max-width":q,"max-height":q,margin:"",transform:""});this.Jm(B);x={transform:x,top:"",left:"",width:l?`${l}px`:"",height:p?`${p}px`:"","max-width":"","max-height":""};q=this.W.cj;var R=this.W.TU,m=this.W.tN;this.r8&&q!=null&&(R=50,q=Math.floor(q/3)*3+1);R=R*.96+2;switch(q){case 0:case 3:case 6:(a=this.W.ii.fontSizeIncrement)&&a>0&&this.W.YM!==2&&this.W.YM!==3&&(R=Math.max(R/(1+a*2),2));x.left=`${R}%`;break;case 1:case 4:case 7:x.left=
`${R}%`;R=0;this.J||(R=this.G.offsetWidth);l||R?(l=l||R+1,x.width=`${l}px`,x["margin-left"]=a?`${l/-2-C/2}px`:`${l/-2}px`):(this.J&&(x.width="max-content"),x.transform+=" translateX(-50%)");break;case 2:case 5:case 8:x.right=`${100-R}%`}a=m*.96+2;switch(q){case 0:case 1:case 2:x.top=`${a}%`;break;case 3:case 4:case 5:x.top=`${a}%`;a=0;this.J||(a=this.element.clientHeight);(p=p||a)?(x.height=`${p}px`,x["margin-top"]=`${p/-2}px`):x.transform+=" translateY(-50%)";break;case 6:case 7:case 8:x.bottom=
`${100-a}%`}g.s4(this.element,x);this.L&&(this.J?p=this.bH:(B=lpt(this,B),p=this.r8?B>0?this.G.offsetHeight/B:0:this.G.offsetHeight/B),this.L.style.height=`${p}px`,this.L.style.width=`${p}px`,this.element.style.paddingLeft=`${p+5}px`,this.element.style.paddingRight=`${p+5}px`,this.J||(B=Number(this.element.style.marginLeft.replace("px",""))-p-5,p=Number(this.element.style.marginRight.replace("px",""))-p-5,this.element.style.marginLeft=`${B}px`,this.element.style.marginRight=`${p}px`))}Jm(B){if(this.type===
0&&this.O.params.ZV!==void 0&&this.experiments.U$("web_enable_popon_asr_captions")){var l=B,p=this.O.params.ZV;if(l.length===0||p<=0)B=[];else{B=[];for(let x=l.length-1;x>=0;x--){var a=l[x];B.unshift(a);let C=lpt(this,B);if(C>p){B.shift();typeof a.text==="string"&&(l=a.text.split("\n"),p=C-p,l.length-p>0&&(a=new Vd(a.start,a.end-a.start,a.priority||0,a.windowId,l.slice(p).join("\n"),a.append,a.W),B.unshift(a)));break}}}}for(a=0;a<B.length&&B[a]===this.Z[a];a++);if(this.s$||this.Z.length>a)a=0,this.s$=
!1,this.Z=[],this.N=this.g8=this.FT=null,g.tz(this.G);for(;a<B.length;a++)xd7(this,B[a])}u9(){return 0}vO(){return 0}toString(){return super.toString()}};var FqT=class{constructor(){this.O=this.time=this.mode=this.A=0;this.D=new okt(this);this.G=new okt(this);this.W=[];this.clear()}clear(){this.O=this.time=this.mode=0;this.W=[];this.reset()}reset(){this.mode=0;this.D.reset(0);this.G.reset(1)}},CX7=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,
74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,
215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255],hEU=class{constructor(){this.type=0}set(B){this.type=B}get(){return this.type}},svt=class{constructor(){this.state=this.iS=this.hq=0}clear(){this.state=0}update(){this.state=this.state===2?1:0}Qa(){return this.state!==0}matches(B,l){return this.Qa()&&B===this.hq&&l===this.iS}},kG7=class{constructor(){this.timestamp=this.W=0}reset(){this.timestamp=
this.W=0}},mx=class{constructor(B){this.G=B;this.O=[];this.W=this.A=this.row=0;this.style=new hEU;this.D=0;for(B=0;B<=15;B++){this.O[B]=[];for(let l=0;l<=32;l++)this.O[B][l]=new kG7}}updateTime(B){for(let l=1;l<=15;++l)for(let p=1;p<=32;++p)this.O[l][p].timestamp=B}debugString(){var B="\n";for(let l=1;l<=15;++l){for(let p=1;p<=32;++p){let a=this.O[l][p];B=a.W===0?B+"_":B+String.fromCharCode(a.W)}B+="\n"}return B}reset(B){for(let l=0;l<=15;l++)for(let p=0;p<=32;p++)this.O[l][p].reset();this.D=B;this.W=
0;this.A=this.row=1}},tZT=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],NST=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],WOT=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,
199,200,202,203,235,206,207,239,212,217,249,219,171,187],PXP=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499],uuj=class{constructor(B){this.O=B;this.G=0;this.style=new hEU;this.V=new mx(this.O);this.N=new mx(this.O);this.text=new mx(this.O);this.A=this.V;this.D=this.N;this.W=this.A}reset(B,l){this.G=l;this.style.set(2);this.A=this.V;this.D=this.N;this.W=this.A;var p=(B<<2)+(l<<1);this.V.reset(p);this.N.reset(p);this.text.reset((B<<
2)+(l<<1)+1)}},okt=class{constructor(B){this.W=B;this.G=0;this.O=new uuj(this.W);this.V=new uuj(this.W);this.A=new svt;this.D=this.O}reset(B){this.G=B;this.A.clear();this.D=this.O;this.O.reset(B,0);this.V.reset(B,1)}};var XKt=class{D(){}};var tC=class extends g.OT{reset(){}};var SF=class extends g.J3{constructor(B,l,p,a,x){super(B,B+l,{priority:p,namespace:"captions"});this.id=a;this.params=x;this.W=[]}toString(){return super.toString()}},Z3=0;var vkP=class extends tC{constructor(B){super();this.D=B;this.pens={};this.L={};this.Z={};this.G="_"+Z3++;this.N={};this.A=this.W=null;this.V=!0}reset(){this.N={};this.A=this.W=null;this.V=!0}O(B,l){B=B.firstChild;B.getAttribute("format");l=l||0;Number.isFinite(l);B=Array.from(B.childNodes);for(var p of B)if(p.nodeType===1)switch(p.tagName){case "head":var a=p;break;case "body":var x=p}if(a){a=Array.from(a.childNodes);for(var C of a)if(C.nodeType===1)switch(C.tagName){case "pen":p=C.getAttribute("id");
a=this.pens;B={};var q=C.getAttribute("p");q&&Object.assign(B,this.pens[q]);q=Is(C,"b");q!=null&&(B.bold=q);q=Is(C,"i");q!=null&&(B.italic=q);q=Is(C,"u");q!=null&&(B.underline=q);q=OR(C,"et");q!=null&&(B.charEdgeStyle=q);q=OR(C,"of");q!=null&&(B.offset=q);q=wa(C,"bc");q!=null&&(B.background=q);q=wa(C,"ec");q!=null&&(B.aV=q);q=wa(C,"fc");q!=null&&(B.color=q);q=OR(C,"fs");q!=null&&q!==0&&(B.fontFamily=q);q=jF(C,"sz");q!==void 0&&(B.fontSizeIncrement=q/100-1);q=jF(C,"bo");q!==void 0&&(B.backgroundOpacity=
q/255);q=jF(C,"fo");q!==void 0&&(B.textOpacity=q/255);q=OR(C,"rb");q!=null&&q!==10&&q!==0&&(B.Ew=q>10?q-1:q);q=OR(C,"hg");q!=null&&(B.W$=q);a[p]=B;break;case "ws":a=C.getAttribute("id");this.Z[a]=oBl(this,C);break;case "wp":a=C.getAttribute("id"),this.L[a]=FOn(this,C)}}if(x){C=[];x=Array.from(x.childNodes);for(G of x)if(G.nodeType===1)switch(G.tagName){case "w":this.W=hBU(this,G,l,!1);(x=this.N[this.W.id])&&x.end>this.W.start&&(x.end=this.W.start);this.N[this.W.id]=this.W;C.push(this.W);break;case "p":var R=
G;B=l;x=[];a=R.getAttribute("w")||this.G;p=!!Is(R,"a");B=(jF(R,"t")||0)+B;q=jF(R,"d")||5E3;p||(!this.V&&this.A&&this.A.windowId===a&&this.A.end>B&&(this.A.end=B),this.A&&this.A.text==="\n"&&(this.A.text=""));let Z=p?6:5;var m=R.getAttribute("p");m=m?this.pens[m]:null;let I=Array.from(R.childNodes);I.length&&(this.V=R.getAttribute("d")!=null);for(R=0;R<I.length;R++){var t=I[R],N=void 0;R>0&&(p=!0);let O;t.nodeType===1&&(O=t);if(O&&O.tagName==="s"){if((t=(t=O.getAttribute("p"))?this.pens[t]:null)&&
t.Ew&&(t.Ew===1?(t=I.slice(R,R+4),t.length===4&&(N=zBn(B,q,a,p,Z,t,this.pens),R+=3)):N=zBn(B,q,a,p,Z,[O],this.pens)),!N){var W=O;N=B;t=q;var P=a,E=p;let Y=W.textContent?W.textContent:"";var k=W.getAttribute("p");k=k?this.pens[k]:null;W=jF(W,"t")||0;N=new Vd(N+W,t-W,Z,P,Y,E,k)}}else N=new Vd(B,q,Z,a,t.textContent||"",p,m);x.push(N);this.A=N}if(x.length>0){x[0].windowId===this.G&&(this.W=hBU(this,G,l,!0),C.push(this.W));for(let O of x)O.windowId=this.W.id,this.W.W.push(O),C.push(O)}}var G=C}else G=
[];return G}};var Lqk=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]),GGx=class extends tC{constructor(B){super();this.V=B;this.W=new Map;this.D=new Map;this.G=new Map;this.A=new Map}reset(){this.A.clear()}O(B,l){B=JSON.parse(B);if(!B)return[];if(B.pens){var p=B.pens,a=0;for(var x of p){p={};var C=x.pParentId;C&&Object.assign(p,this.W.get(C));x.bAttr&&(p.bold=!0);x.iAttr&&(p.italic=!0);x.uAttr&&(p.underline=!0);C=x.ofOffset;C!=null&&(p.offset=C);x.szPenSize!==void 0&&(p.fontSizeIncrement=x.szPenSize/100-1);
C=x.etEdgeType;C!=null&&(p.charEdgeStyle=C);x.ecEdgeColor!==void 0&&(p.aV=eF(x.ecEdgeColor));C=x.fsFontStyle;C!=null&&C!==0&&(p.fontFamily=C);x.fcForeColor!==void 0&&(p.color=eF(x.fcForeColor));x.foForeAlpha!==void 0&&(p.textOpacity=x.foForeAlpha/255);x.bcBackColor!==void 0&&(p.background=eF(x.bcBackColor));x.boBackAlpha!==void 0&&(p.backgroundOpacity=x.boBackAlpha/255);(C=x.rbRuby)&&C!==10&&(p.Ew=C>10?C-1:C,p.textEmphasis=Lqk.get(p.Ew));x.hgHorizGroup&&(p.W$=x.hgHorizGroup);this.W.set(a++,p)}}if(B.wsWinStyles){a=
B.wsWinStyles;x=0;for(var q of a)a={},(p=q.wsParentId)?Object.assign(a,this.G.get(p)):Object.assign(a,this.V),q.mhModeHint!==void 0&&(a.yV=q.mhModeHint),q.juJustifCode!==void 0&&(a.textAlign=q.juJustifCode),q.pdPrintDir!==void 0&&(a.YM=q.pdPrintDir),q.sdScrollDir!==void 0&&(a.f$=q.sdScrollDir),q.wfcWinFillColor!==void 0&&(a.windowColor=eF(q.wfcWinFillColor)),q.wfoWinFillAlpha!==void 0&&(a.windowOpacity=q.wfoWinFillAlpha/255),this.G.set(x++,a)}if(B.wpWinPositions){x=B.wpWinPositions;q=0;for(var R of x)x=
{},(a=R.wpParentId)&&Object.assign(x,this.D.get(a)),R.ahHorPos!==void 0&&(x.TU=R.ahHorPos),R.apPoint!==void 0&&(x.cj=R.apPoint),R.avVerPos!==void 0&&(x.tN=R.avVerPos),R.ccCols!==void 0&&(x.Ro=R.ccCols),R.rcRows!==void 0&&(x.ZV=R.rcRows),this.D.set(q++,x)}if(B.events){B=B.events;R=[];for(let f of B)if(q=(f.tStartMs||0)+l,x=f.dDurationMs||0,f.id)a=String(f.id),B=s5b(this,f,q,x,a),R.push(B),this.A.set(a,B);else{f.wWinId?a=f.wWinId.toString():(a="_"+Z3++,B=s5b(this,f,q,x,a),R.push(B),this.A.set(a,B));
B=R;var m=f;x===0&&(x=5E3);p=this.A.get(a);let qB=(C=!!m.aAppend)?6:5,Di=m.segs,JE=null;m.pPenId&&(JE=this.W.get(m.pPenId));for(m=0;m<Di.length;m++){var t=Di[m],N=t.utf8;if(N){var W=t.tOffsetMs||0;let vW=null;t.pPenId&&(vW=this.W.get(t.pPenId));if((p.params.yV!=null?p.params.yV:p.W.length>1?1:0)===2&&C&&N==="\n")continue;t=null;var P=[],E;if(E=vW&&vW.Ew===1)a:{E=Di;var k=m;if(k+3>=E.length||!E[k+1].pPenId||!E[k+2].pPenId||!E[k+3].pPenId){E=!1;break a}var G=E[k+1].pPenId;(G=this.W.get(G))&&G.Ew&&G.Ew===
2?(G=E[k+2].pPenId,G=this.W.get(G),!G||!G.Ew||G.Ew<3?E=!1:(G=E[k+3].pPenId,E=(G=this.W.get(G))&&G.Ew&&G.Ew===2?!0:!1)):E=!1}if(E)W=Di[m+1].utf8,t=Di[m+3].utf8,E=Di[m+2].utf8,k=this.W.get(Di[m+2].pPenId),N=Huj(N,W,E,t,k),t=new Vd(q,x,qB,a,N,C,vW),m+=3;else{if(N.indexOf("<")>-1){P=vW;E=JE;k=q;G=x;var Z=W,I=qB,O=C;let yp=[];var Y=kx(`<html>${N}</html>`);if(!Y.getElementsByTagName("parsererror").length&&Y.firstChild?.childNodes.length)for(let AE of Y.firstChild.childNodes){Y=AE.textContent?.replace(/\n/g,
"")??"";if(AE.nodeType===3&&(!Y||Y.match(/^ *$/)!=null))continue;let My={};Object.assign(My,P||E);switch(AE?.tagName){case "b":My.bold=!0;break;case "i":My.italic=!0;break;case "u":My.underline=!0}yp.push(new Vd(k+Z,G-Z,I,p.id,Y,O,My))}P=yp}P.length||(P=[new Vd(q+W,x-W,qB,p.id,N,C,vW||JE)])}if(P.length)for(let yp of P)B.push(yp),p.W.push(yp);else t&&(B.push(t),p.W.push(t))}C=!0}}l=R}else l=[];return l}};var cg7=class extends Rp{constructor(B,l,p){super(B);this.videoData=l;this.audioTrack=p;this.Z=l.eF}N(B,l,p){Ikt(this.videoData.videoId,B.vssId,p.Qo)}D(B){if(this.audioTrack)for(let l of this.audioTrack.captionTracks)sR(this.W,l);B.GU()}};var mjn=class extends ih{constructor(B,l,p,a,x,C,q,R,m,t){super(B,l,p,a,x,C,q,R,m,t);this.type=1}Jm(B){var l=this.O.W;super.Jm(B);for(B=B.length;B<l.length;B++){let x=l[B],C;if(a&&x.W===p)C=a;else{C={};Object.assign(C,x.W);Object.assign(C,djl);var p=x.W;var a=C}xd7(this,x,C)}}},djl={b2:!0};var kPl=class extends XKt{constructor(B,l){super();this.trackData=B;this.V=l;this.version=this.G=this.O=this.byteOffset=0;this.A=[];this.W=new DataView(this.trackData)}D(B,l,p,a,x){if(p<a){let C="_"+Z3++;p=p/1E3-this.V;a=a/1E3-this.V;B=new SF(p,a-p,5,C,{textAlign:0,cj:0,TU:l*2.5,tN:B*5.33});x=new Vd(p,a-p,5,C,x);this.A.push(B);this.A.push(x)}}},VrU=class extends tC{constructor(B,l){super();this.A=B;this.D=l;this.track=this.D.languageName==="CC3"?4:0;this.W=new FqT;this.W.A=1<<this.track}O(B){B=new kPl(B,
this.A);if(uWl(B)){for(;B.byteOffset<B.W.byteLength;)for(B.version===0?B.O=$x(B)*(1E3/45):B.version===1&&(B.O=$x(B)*4294967296+$x(B)),B.G=Ap(B);B.G>0;B.G--){var l=Ap(B);let p=Ap(B),a=Ap(B);l&4&&(l&3)===this.track&&(this.track===0||this.track===1)&&(l=this.W,l.W.push({time:B.O,type:this.track,UN:p,eB:a,order:l.W.length}))}mdP(this.W,B);return B.A}return[]}reset(){this.W.clear()}};var trk=class extends ih{constructor(B,l,p,a,x,C,q,R,m,t){super(B,l,p,a,x,C,q,R,m,t);this.type=2;this.kh=[];this.DB=this.uH=this.Kj=0;this.Nc=NaN;this.jm=0;this.BO=null;this.TJ=new g.wL(this.Om,433,this);this.L&&(t.createClientVe(this.L,this,167342),this.Wi(this.L,"click",()=>{t.logClick(this.L)}),B=new g.o9(this.element,!0),g.c(this,B),B.subscribe("hoverstart",()=>{t.logVisibility(this.L,!0)},this));
g.Kz(this.element,"ytp-caption-window-rollup");g.c(this,this.TJ);g.s4(this.element,"overflow","hidden")}cO(){var B=this.TJ;B.stop();B.fN()}Om(){this.element.removeEventListener("transitionend",this.Om,!1);g.ys(this.element,"ytp-rollup-mode");this.U(this.BO,!0)}vO(){return this.V?this.DB:this.uH}u9(){return this.V?this.uH:this.DB}U(B,l){this.BO=B;if(this.O.params.ZV){var p=0;for(let a=0;a<this.Z.length&&p<B.length;a++)this.Z[a]===B[p]&&p++;p>0&&p<B.length&&(B=this.Z.concat(B.slice(p)));this.jm=this.DB;
this.uH=this.DB=0;super.U(B);GPT(this,l)}super.U(B)}};var ZrU=class{constructor(B,l,p,a){this.B=B;this.V=l;this.logger=p;this.L_=a;this.nA=[];this.W=null;this.O=[];this.xC=[];this.A=null;B=g.Qi(this.B.Y().experiments,"html5_override_micro_discontinuities_threshold_ms");this.D=B>0?B:10}unload(){this.A!=null&&(this.B.removeEventListener("sabrCaptionsDataLoaded",this.A),this.A=null);this.nA=[];this.W=null;this.O=[];this.B.hm("sabrCaptionsBufferedRangesUpdated",this.nA)}G(B){return{formatId:g.Gd(B.info.nj.info,this.L_),zo:B.info.zo+(this.L_?0:1),startTimeMs:B.info.O*
1E3,durationMs:B.info.N*1E3}}};var Skn=class extends Rp{constructor(B,l){super(l);this.A=B;this.B=l;this.logger=new g.Me("caps");this.L=this.J=null;this.U=new ZrU(this.B,this,this.logger,this.A.L_)}N(B,l,p){this.O();l=B.getId();l=l!=null&&l in this.A.W?this.A.W[l]:null;l||(l=B.languageCode,l=this.A.isManifestless?gBl(this,l,"386"):gBl(this,l));l&&(this.L=B,this.J=l,SS7(this.U,p),this.B.hm("sabrCaptionsTrackChanged",g.Gd(l.info,this.A.L_)))}D(B){var l=this.A.isManifestless?Ipk(this,"386"):Ipk(this);for(let p of l)sR(this.W,p);B.GU()}O(){this.L&&
(this.L=this.J=null,this.U.unload(),this.B.hm("sabrCaptionsTrackChanged",null))}V(){return""}};var Oul="WEBVTT".split("").map(B=>B.charCodeAt(0)),Q5l=class extends tC{constructor(){super()}O(B,l){B instanceof ArrayBuffer&&(B=g.ki(new Uint8Array(B)));
var p=[];B=B.split(jvT);for(let k=1;k<B.length;k++){var a=B[k],x=l;if(a!==""&&!gkT.test(a)){var C=N6.exec(a);if(C&&C.length>=4){var q=Qd(C[1]),R=Qd(C[2])-q;q+=x;var m=(C=C[3])?C.split(" "):[];C={};var t=null;var N="";var W=null,P="";for(let G of m){m=G.split(":");if(m.length!==2)continue;var E=m[1];switch(m[0]){case "line":m=E.split(",");m[0].endsWith("%")&&(t=m[0],C.tN=Number.parseInt(t,10),m.length===2&&(N=m[1].trim()));break;case "position":m=E.split(",");W=m[0];C.TU=Number.parseInt(W,10);m.length===
2&&(P=m[1].trim());break;case "align":switch(E){case "start":C.textAlign=0;break;case "middle":C.textAlign=2;break;case "end":C.textAlign=1}}}t||N||(N="end");if(!W)switch(C.textAlign){case 0:C.TU=0;break;case 1:C.TU=100;break;case 2:C.TU=50}if(C.textAlign!=null){t=0;switch(N){case "center":t+=3;break;case "end":t+=6;break;default:t+=0}switch(P){case "line-left":t+=0;break;case "center":t+=1;break;case "line-right":t+=2;break;default:switch(C.textAlign){case 0:t+=0;break;case 2:t+=1;break;case 1:t+=
2}}N=t<0||t>8?7:t;C.cj=N}a=a.substring(N6.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");P=C;C={};if(a.indexOf("<")<0&&a.indexOf("&")<0)x=wJx(q,R,5,P),q=new Vd(q,R,5,x.id,a,!1,g.gY(C)?void 0:C),p.push(x),p.push(q),x.W.push(q);else for(N=a.split(I1E),N.length===1?(a=5,P=wJx(q,R,a,P)):(t=a=6,P=Object.assign({Ro:32},P),P=new SF(q,R,t,"_"+Z3++,P)),p.push(P),t=q,W=0;W<N.length;W++)if(m=N[W],W%2===0){E=kx(`<html>${m}</html>`);let G;E.getElementsByTagName("parsererror").length?(G=E.createElement("span"),
G.appendChild(E.createTextNode(m))):G=E.firstChild;eBn(this,t,R-(t-q),a,P,W>0,G,C,p)}else t=Qd(m)+x}N6.lastIndex=0}}return p}},gkT=/^NOTE/,jvT=/(?:\r\n|\r|\n){2,}/,N6=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),I1E=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");var Orx=class extends g.OT{constructor(B,l){super();this.B=B;this.X=l;this.W=null;this.QF=this.B.N5();this.logger=new g.Me("caps")}clear(){this.W&&this.W.dispose();this.W=null}reset(){this.W&&this.W.reset()}VY(){super.VY();this.clear()}};var yfn={windowColor:"#080808",windowOpacity:0,textAlign:2,cj:7,TU:50,tN:100,isDefault:!0,ii:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}},nBk={windowColor:"#080808",windowOpacity:0,textAlign:0,cj:7,TU:50,tN:100,isDefault:!0,ii:{background:"#080808",backgroundOpacity:.7,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.yG("captions",class extends g.hN{constructor(B){super(B);this.B=B;this.kh=[];this.DB={};this.g8={};this.L=!1;this.O="NONE";this.W=this.Z=this.U=this.d8=this.Hi=null;this.f_={GU:()=>{this.GU()},
Qo:(a,x,C,q,R=0)=>{var m=Number(this.videoData.Y().Mc().W.QY(g.G9P)??0);R>0&&m>0&&this.videoData.lengthSeconds>0&&R/this.videoData.lengthSeconds>m?this.B.K("tts",{dropcap:R}):this.Qo(a,x,C,q)}};
this.mf=this.A=null;this.X=this.B.Y();this.videoData=this.B.getVideoData();this.Om=this.B.TI();this.G={ii:{}};this.V={ii:{}};g.qt(this.videoData)?this.O="OFFLINE":g.Rmp(this.videoData,this.B)?this.O="HLS":j5B(this.videoData,this.B)?this.O="SABR_LIVE":g.mhP(this.videoData,this.B)?this.O="LIVE":this.videoData.captionTracks.length?this.O="INNERTUBE":this.videoData.TJ&&(this.O="TTS");this.s$=this.X.controlsType==="3";this.Kj=new Orx(this.B,this.X);this.Cj=new g.Q8(this);this.N=new g.zE({j:"div",O$:"ytp-caption-window-container",
fj:{id:"ytp-caption-window-container"}});this.uH={top:0,right:0,bottom:0,left:0,width:1,height:1};var l=null,p=g.sD("yt-html5-player-modules::subtitlesModuleData");p&&(l=new g.Rx(p));this.storage=l;l=B.LA();this.j1=!!l?.Nc();this.r8=!!l?.s$();this.D=fd(this);this.J=KOW(this);g.c(this,this.Kj);this.D?this.FT=this.Nc=null:(this.Nc=new g.IF(this.sm,void 0,this),g.c(this,this.Nc),this.FT=new g.wL(this.jm,2E3,this),g.c(this,this.FT));g.c(this,this.Cj);g.f3(this.player,this.N.element,4);g.c(this,this.N);
this.D||this.Cj.Wi(B,"resize",this.Jm);l=g.NY(this.X)&&!g.h8()&&!this.B.isFullscreen();p=this.X.Mc().W.QY(g.AbU)&&g.g3(this.X)==="MWEB"&&g.pI;(this.ot=(l||p)&&!this.D&&!this.J)&&this.Cj.Wi(B,l?"resize":"fullscreentoggled",this.vO);this.Cj.Wi(B,"onPlaybackAudioChange",this.tg);this.Cj.Wi(B,g.E9("captions"),a=>{this.onCueRangeEnter(a)});
this.Cj.Wi(B,g.DO("captions"),a=>{this.onCueRangeExit(a)});
Yx(this,hp()||{});g.kI(this.player,"onCaptionsModuleAvailable");this.O==="HLS"&&this.D&&(B=this.B.LA().mq(),this.r8&&this.Cj.Wi(B.textTracks,"addtrack",this.u9))}VY(){if(this.D||this.J){let B=this.B.LA();B&&!B.iH()&&B.L()}else Kd(this,!1);super.VY()}mK(){if(this.s$)return this.D||this.J;if(this.O==="HLS")return this.D;var B=this.getAudioTrack();if(pKl(this)){if(!B.captionTracks.length)return!1;if(!this.W)return!0}B=os(B,g.Lk(this.X));return B==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?!0:B==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"?
ra(this):UR(this)||ra(this)?!0:l1t(this)}load(){super.load();this.Z=this.getAudioTrack();if(this.W)this.A&&(this.Kj.clear(),this.D?a1b(this,!0):this.player.getPresentingPlayerType()!==3&&this.W.N(this.A,"json3",this.f_),this.O!=="HLS"&&this.D||this.J||BQ(this)||g.kI(this.player,"captionschanged",bL(this.A)));else{if(this.O==="OFFLINE")var B=new cg7(this.player,this.videoData,this.getAudioTrack());else this.O==="SABR_LIVE"?B=new Skn(this.videoData.W,this.player):this.O==="HLS"?B=new Ekn(this.player):
this.O==="LIVE"?B=new Hrp(this.videoData.W,this.player):this.O==="INNERTUBE"?B=new Djt(this.player,this.videoData,this.getAudioTrack()):(B=this.videoData,B=new zEj(this.player,this.videoData.TJ,this.videoData.videoId,B.captionsLanguagePreference||B.Am.captionsLanguagePreference||g.AV(B,"yt:cc_default_lang")||B.Am.Om,this.videoData.sc,this.videoData.eventId));this.W=B;g.c(this,this.W);this.W.D(this.f_)}}unload(){this.D&&this.A?a1b(this,!1):(this.FT&&this.FT.j7(),this.player.XM("captions"),this.kh=
[],this.W&&this.W.O(),this.Kj.clear(),this.U&&this.player.AB(this.U),this.Jm());super.unload();this.player.BA();g.kI(this.player,"captionschanged",{})}create(){this.mK()&&this.load();var B;a:{if(this.X.S("web_player_nitrate_promo_tooltip")&&this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.enableTouchCaptionsNitrate&&(B=this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.captionTracks))for(let l of B)if(l.kind==="asr"&&l.languageCode==="en"){B=
!0;break a}B=!1}B&&this.B.hm("showpromotooltip",this.N.element)}GU(){var B=os(this.player.getAudioTrack(),g.Lk(this.X));var l=B==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?ps(this,this.L):B==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"&&ra(this)?lh(this):UR(this)||this.L||l1t(this)?ps(this,this.L):ra(this)?lh(this):null;if(this.O!=="HLS"&&this.D||this.J){let p=this.W.W.W(!0);B=[];for(let a=0;a<p.length;a++){let x=p[a],C=g.Rg("TRACK");C.setAttribute("kind","subtitles");C.setAttribute("label",g.KV(x));C.setAttribute("srclang",
g.nV(x));C.setAttribute("id",x.toString());this.J||C.setAttribute("src",this.W.V(x,"vtt"));x===l&&C.setAttribute("default","1");B.push(C)}l=this.B.LA();l.uH(B);B=l.mq();this.r8&&this.Cj.Wi(B.textTracks,"change",this.hy)}else!this.A&&l&&q6(this,l),g.kI(this.player,"onCaptionsTrackListChanged"),g.uo(this.player,"onApiChange")}getTrackById(B){var l=this.W.W.W(!0);for(let p=0;p<l.length;p++)if(l[p].toString()===B)return l[p];return null}hy(){var B=this.B.LA().mq().textTracks,l=null;for(let p=0;p<B.length;p++)B[p].mode===
"showing"&&(l=this.getTrackById(B[p].id));(this.loaded?this.A:null)!==l&&q6(this,l,!0)}u9(){this.W?.D(this.f_)}wq(){!this.A&&this.D||this.unload()}Qo(B,l,p,a){if(B){Cs(this,this.A??void 0);this.W.Cj()&&(this.kh=[],this.B.XM("captions"),zt(this.Nc),this.Kj.reset());a:{var x=this.Kj;a=a||0;p=$dt(x,B,p||0);B=[];try{for(let I of p){let O=I.trackData,Y=I.Fr,f=x.X.S("safari_live_drm_captions_fix");if(typeof O!=="string"){p=B;var C=p.concat;if(f&&TSP(O))var q=fpE(x,O,Y);else{var R=x,m=l,t=O,N=Y,W=a;if(!XJE(t))throw Error("Invalid binary caption track data");
R.W||(R.W=new VrU(W,m));q=R.W.O(t,N)}var P=C.call(p,q)}else{if(O.substring(0,6)==="WEBVTT")var E=B.concat(fpE(x,O,Y));else{p=B;var k=p.concat;b:{m=x;R=l;if(O[0]==="{")try{m.W||(m.W=new GGx(YSj(R)));var G=m.W.O(O,Y);break b}catch(JE){g.DE(JE);G=[];break b}let qB=kx(O);if(!qB||!qB.firstChild){let JE=Error("Invalid caption track data");JE.params=O;throw JE;}if(qB.firstChild.tagName==="timedtext"){if(Number(qB.firstChild.getAttribute("format"))===3){t=qB;m.W||(m.W=new vkP(YSj(R)));G=m.W.O(t,Y);break b}let JE=
Error("Unsupported subtitles format in web player (Format2)");JE.params=O;throw JE;}if(qB.firstChild.tagName==="transcript"){let JE=Error("Unsupported subtitles format in web player (Format1)");JE.params=O;throw JE;}let Di=Error("Invalid caption track data");Di.params=O;throw Di;}E=k.call(p,G)}P=E}B=P}var Z=B;break a}catch(I){g.HR(x.logger,187101178,`Captions parsing failed: ${I.message}. `);x.clear();Z=[];break a}Z=void 0}this.X.S("html5_sabr_live_support_subfragmented_captions")&&this.W instanceof
Skn&&(l=this.W.U,x=[],Z.length>0&&(x=Z.slice(l.O.length)),l.O=!l.W||l.W.info.Qf?[]:Z,Z=x);Z.length>0&&(l=this.A,this.XV(l,!!l,BQ(this)?"g":this.L?"m":"s"));this.player.AB(Z,void 0,this.O==="LIVE"||this.O==="SABR_LIVE");!this.L||this.J||BQ(this)||g.sJ(this.X)||g.Hx(this.X)||g.Wx(this.X)||this.X.Z==="shortspage"||this.player.isInline()||(this.FT.j7(),Z=bup({cj:0,TU:5,tN:5,ZV:2,textAlign:0,YM:0,lang:"en-GB"}),this.d8=[Z],l=["Click "," for settings"],this.Hi||(x=new g.slt({j:"svg",fj:{height:"100%",version:"1.1",
viewBox:"0 0 36 36",width:"100%"},Lj:[{j:"path",eM:!0,fj:{d:"m 23.94,18.78 c .03,-0.25 .05,-0.51 .05,-0.78 0,-0.27 -0.02,-0.52 -0.05,-0.78 l 1.68,-1.32 c .15,-0.12 .19,-0.33 .09,-0.51 l -1.6,-2.76 c -0.09,-0.17 -0.31,-0.24 -0.48,-0.17 l -1.99,.8 c -0.41,-0.32 -0.86,-0.58 -1.35,-0.78 l -0.30,-2.12 c -0.02,-0.19 -0.19,-0.33 -0.39,-0.33 l -3.2,0 c -0.2,0 -0.36,.14 -0.39,.33 l -0.30,2.12 c -0.48,.2 -0.93,.47 -1.35,.78 l -1.99,-0.8 c -0.18,-0.07 -0.39,0 -0.48,.17 l -1.6,2.76 c -0.10,.17 -0.05,.39 .09,.51 l 1.68,1.32 c -0.03,.25 -0.05,.52 -0.05,.78 0,.26 .02,.52 .05,.78 l -1.68,1.32 c -0.15,.12 -0.19,.33 -0.09,.51 l 1.6,2.76 c .09,.17 .31,.24 .48,.17 l 1.99,-0.8 c .41,.32 .86,.58 1.35,.78 l .30,2.12 c .02,.19 .19,.33 .39,.33 l 3.2,0 c .2,0 .36,-0.14 .39,-0.33 l .30,-2.12 c .48,-0.2 .93,-0.47 1.35,-0.78 l 1.99,.8 c .18,.07 .39,0 .48,-0.17 l 1.6,-2.76 c .09,-0.17 .05,-0.39 -0.09,-0.51 l -1.68,-1.32 0,0 z m -5.94,2.01 c -1.54,0 -2.8,-1.25 -2.8,-2.8 0,-1.54 1.25,-2.8 2.8,-2.8 1.54,0 2.8,1.25 2.8,2.8 0,1.54 -1.25,2.8 -2.8,2.8 l 0,0 z",
fill:"#fff"}}]}),g.c(this,x),this.Hi=x.element),x=Z.end-Z.start,(P=g.KV(this.A))&&this.d8.push(new Vd(Z.start,x,0,Z.id,P)),this.d8.push(new Vd(Z.start,x,0,Z.id,l[0]),new Vd(Z.start,x,0,Z.id,this.Hi,!0),new Vd(Z.start,x,0,Z.id,l[1],!0)),this.player.AB(this.d8),g.e4(this.FT));!this.L||this.J||BQ(this)||(this.X.S("enable_player_captions_persistence_state_machine")?yd(this,!0):g.Lk(this.X)?ap(this,!0):xj(this,!0),this.Z&&(this.Z.D=this.A),this.player.BA());this.L=!1}}onCueRangeEnter(B){this.kh.push(B);
zt(this.Nc)}onCueRangeExit(B){g.$S(this.kh,B);this.W instanceof Hrp&&this.W.J&&this.player.JC([B]);zt(this.Nc)}getCaptionWindowContainerId(){return this.N.element.id}jm(){Udk(this,this.d8);this.d8=null}sm(){if(!this.ot||!this.D){this.Nc.stop();g.I1(this.g8);this.kh.sort(g.Pg);var B=this.kh;if(this.U){let l=g.VZ(B,function(p){return this.U.indexOf(p)===-1},this);
l.length&&(B=l)}for(let l of B)l instanceof SF?qkl(this,l):irb(this,l);for(let [l,p]of Object.entries(this.DB)){let a=l,x=p;this.g8[a]?(x.element.parentNode||(x instanceof trk||x instanceof mjn||g.uw(this.DB,(C,q)=>{q!==a&&C.O.params.cj===x.O.params.cj&&C.O.params.TU===x.O.params.TU&&C.O.params.tN===x.O.params.tN&&(C.dispose(),delete this.DB[q]);return q===a},this),this.N.element.appendChild(x.element)),x.U(this.g8[a])):(x.dispose(),delete this.DB[a])}}}aI(){Yx(this,{},!0);
g.kI(this.player,"captionssettingschanged")}Zo(){var B=this.X.S("enable_player_captions_new_style_defaults")?nBk:yfn,l=B.ii;B={background:l.background,backgroundOpacity:l.backgroundOpacity,charEdgeStyle:l.charEdgeStyle,color:l.color,fontFamily:l.fontFamily,fontSizeIncrement:l.fontSizeIncrement,fontStyle:l.bold&&l.italic?3:l.bold?1:l.italic?2:0,textOpacity:l.textOpacity,windowColor:B.windowColor,windowOpacity:B.windowOpacity};l=hp()||{};l.background!=null&&(B.background=l.background);l.backgroundOverride!=
null&&(B.backgroundOverride=l.backgroundOverride);l.backgroundOpacity!=null&&(B.backgroundOpacity=l.backgroundOpacity);l.backgroundOpacityOverride!=null&&(B.backgroundOpacityOverride=l.backgroundOpacityOverride);l.charEdgeStyle!=null&&(B.charEdgeStyle=l.charEdgeStyle);l.charEdgeStyleOverride!=null&&(B.charEdgeStyleOverride=l.charEdgeStyleOverride);l.color!=null&&(B.color=l.color);l.colorOverride!=null&&(B.colorOverride=l.colorOverride);l.fontFamily!=null&&(B.fontFamily=l.fontFamily);l.fontFamilyOverride!=
null&&(B.fontFamilyOverride=l.fontFamilyOverride);l.fontSizeIncrement!=null&&(B.fontSizeIncrement=l.fontSizeIncrement);l.fontSizeIncrementOverride!=null&&(B.fontSizeIncrementOverride=l.fontSizeIncrementOverride);l.fontStyle!=null&&(B.fontStyle=l.fontStyle);l.fontStyleOverride!=null&&(B.fontStyleOverride=l.fontStyleOverride);l.textOpacity!=null&&(B.textOpacity=l.textOpacity);l.textOpacityOverride!=null&&(B.textOpacityOverride=l.textOpacityOverride);l.windowColor!=null&&(B.windowColor=l.windowColor);
l.windowColorOverride!=null&&(B.windowColorOverride=l.windowColorOverride);l.windowOpacity!=null&&(B.windowOpacity=l.windowOpacity);l.windowOpacityOverride!=null&&(B.windowOpacityOverride=l.windowOpacityOverride);return B}zw(B,l){var p={};Object.assign(p,hp());Object.assign(p,B);Yx(this,p,l);g.kI(this.player,"captionssettingschanged")}Jm(){!this.D&&this.loaded&&(g.hl(this.DB,function(B,l){B.dispose();delete this.DB[l]},this),this.sm())}OR(B,l){switch(B){case "fontSize":if(isNaN(l))break;
B=g.Jl(l,-2,4);this.zw({fontSizeIncrement:B});return B;case "reload":l&&!this.D&&q6(this,this.A,!0);break;case "stickyLoading":l!==void 0&&this.X.N&&(this.X.S("enable_player_captions_persistence_state_machine")?yd(this,!(!l||!l.userInitiated)):g.Lk(this.X)?ap(this,!!l):xj(this,!!l));break;case "track":return NJE(this,l);case "tracklist":return this.W?g.Z0(this.W.W.W(!(!l||!l.includeAsr)),p=>bL(p)):[];
case "translationLanguages":return this.W?this.W.Z.map(p=>Object.assign({},p)):[];
case "sampleSubtitles":this.D||l===void 0||Kd(this,!!l);break;case "sampleSubtitlesCustomized":this.D||Kd(this,!!l,l);break;case "recommendedTranslationLanguages":return g.v7();case "defaultTranslationSourceTrackIndices":return this.W?this.W.uH:[]}}getOptions(){var B="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.X.N&&B.push("stickyLoading");return B}WA(){var B=this.A;if(this.B.nJ("captions")){if(this.X.S("html5_modify_caption_vss_logging"))return(B=this.videoData.X4??
null)?{cc:g.yb(B)}:{};if(B){let l=B.vssId;B.translationLanguage&&l&&(l=`t${l}.${g.nV(B)}`);return{cc:l}}}return{}}T7(B){this.isSubtitlesOn()?(this.X.S("enable_player_captions_persistence_state_machine")&&B?yd(this,!1):g.Lk(this.X)?ap(this,!1):xj(this,!1),Cs(this),q6(this,null,!0)):this.v8(B)}v8(B){var l=BQ(this)||!this.A?ps(this,!0):this.A;l&&this.w6(l.vssId,"m");this.isSubtitlesOn()||q6(this,l,this.X.S("enable_player_captions_persistence_state_machine")?B:!0)}isSubtitlesOn(){return!!this.loaded&&
!!this.A&&!BQ(this)}tg(){var B=BQ(this);ra(this,B)?q6(this,this.getAudioTrack().W,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),pKl(this)&&(this.L=!1,this.A=null,this.W&&(this.W.dispose(),this.W=null)),this.mK()&&(B?q6(this,ps(this,!1),!1):this.load()))}f4(B){if(this.X.experiments.U$("web_enable_captions_set_target_container")&&B!==this.mf){var l=this.N.element;l.parentNode&&g.Wq(l);(this.mf=B)?(this.mf.appendChild(l),l.style.position="absolute",l.style.bottom="0",l.style.left=
"0",l.style.width="100%",l.style.height="auto",l.style.top="auto"):(g.f3(this.player,l,4),l.style.position="absolute",l.style.bottom="auto",l.style.left="0",l.style.width="100%",l.style.height="100%",l.style.top="0");this.Jm()}}M3(B){B&&(this.uH={top:B.top,right:B.right,bottom:B.bottom,left:B.left,width:1-B.left-B.right,height:1-B.top-B.bottom},this.N.element.style.top=`${this.uH.top*100}%`,this.N.element.style.left=`${this.uH.left*100}%`,this.N.element.style.width=`${this.uH.width*100}%`,this.N.element.style.height=
`${this.uH.height*100}%`,this.N.element.style.position="absolute",B=REE(this))&&(this.N.element.style.width=`${B.width}px`,this.N.element.style.height=`${B.height}px`)}onVideoDataChange(B,l){B==="newdata"&&(this.videoData=l,this.loaded&&this.unload(),this.L=!1,this.A=null,this.W&&(this.W.dispose(),this.W=null,g.kI(this.player,"captionschanged",{})),this.mK()&&this.load())}getAudioTrack(){return this.player.getAudioTrack()}vO(){if(this.X.Mc().W.QY(g.AbU)){if(this.loaded&&this.unload(),this.s$=this.B.isFullscreen()||
this.X.controlsType==="3",this.D=fd(this),this.J=KOW(this),this.D||this.J){var B=this.B.LA();B&&!B.iH()&&B.L();this.GU()}}else(B=this.B.LA())&&!B.iH()&&B.L(),this.B.isFullscreen()?(this.D=this.s$=!0,this.loaded&&this.GU()):(this.s$=this.X.controlsType==="3",this.D=fd(this));q6(this,this.A)}bH(){var B=this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.openTranscriptCommand;B&&g.s_(this.player,"innertubeCommand",B)}XV(B,l,p){var a=/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,x="";B&&
(x=B.vssId,x=x.replace(a,""));var C="";B&&B.getId()&&(C=B.getId()||"");B&&B.getXtags()&&(B=B.getXtags(),B=B.replace(a,""),C=C.concat(`;${B}`));this.O==="HLS"&&(C="");this.B.XV(l?x:"",l?C:"",p)}w6(B,l){B=(B||"").replace(/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,"");B.length>0&&this.B.w6(B,l)}});})(_yt_player);
